#!/usr/bin/env node
/**
 * `openapi/openapi.json` → `src/kaaljyoti/generated/*.py`.
 *
 * Design decision 3: generated frozen dataclasses, our generator. This follows
 * the Dart and PHP generators (`packages/sdk-dart/tool/gen.mjs`,
 * `packages/sdk-php/tool/gen.mjs`) rule for rule — the same `REQUEST_NAMES`
 * table, the same shape-based dedupe so `Birth`, `CalculationOptions` and
 * `TimeWindow` exist once rather than 35 times, the same hand-picked names for
 * the four shapes that dedupe into something a path-derived name would not
 * describe, `LabelledId` shared, `null`-only fields as the widest type the
 * language has (`Any`), `MaitriDocument` as a wrapper around the map it is,
 * and reference rows left untyped. The four SDKs are read side by side, so a
 * shape must not be `ChalitHouses` in Dart and `ChalitDocumentEqual` here.
 *
 * Field names are the wire names, which are already snake_case. The few that
 * are not a usable Python attribute — `from`, and the capitalised planet keys
 * of `TransitScanDocumentNatalPoints` — are renamed (`from_`, `jupiter`), and
 * only those classes carry a `_WIRE` table saying what they were renamed from.
 *
 * What it writes:
 *
 *   src/kaaljyoti/generated/__init__.py     every generated public name
 *   src/kaaljyoti/generated/_json.py        cast helpers and KaaljyotiFormatError
 *   src/kaaljyoti/generated/labelled_id.py  the one shape every document shares
 *   src/kaaljyoti/generated/models.py       every request, document and nested class
 *   src/kaaljyoti/generated/operations.py   the operation table the contract test walks
 *   src/kaaljyoti/generated/version.py      the two version constants
 *
 * The output is committed and formatted with `ruff format` and
 * `ruff check --fix`; `--check` regenerates into `.gen-check/` inside the
 * package (so ruff reads the same `pyproject.toml`), formats that copy the
 * same way, and compares byte for byte, so CI fails on a stale file rather
 * than shipping models that describe an API we no longer have.
 *
 * Usage: `node tool/gen.mjs [--check]`. `RUFF` overrides the ruff binary
 * (default `.venv/bin/ruff`, else `ruff` on PATH, as CI installs it with pip
 * and has no `.venv`).
 */

import { spawn } from 'node:child_process';
import { existsSync } from 'node:fs';
import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const packageDir = dirname(dirname(fileURLToPath(import.meta.url)));
const schemaFile = join(packageDir, '../../openapi/openapi.json');
const outRel = 'src/kaaljyoti/generated';
const outDir = join(packageDir, outRel);
const checkRel = '.gen-check';
const checkDir = join(packageDir, checkRel);
const venvRuff = join(packageDir, '.venv/bin/ruff');
const ruff = process.env.RUFF ?? (existsSync(venvRuff) ? venvRuff : 'ruff');

const HEADER = (
  what,
) => `"""GENERATED by \`pnpm --filter sdk-python run gen\` from openapi/openapi.json.

Do not edit by hand: \`pnpm --filter sdk-python run gen:check\` fails the build
when this file and the snapshot disagree.

${what}
"""
`;

// ---------------------------------------------------------------------------
// The shared naming contract
// ---------------------------------------------------------------------------

/**
 * Request and document names, mirroring `packages/sdk-ts/src/types.ts` and
 * the Dart and PHP generators.
 *
 * A missing entry is a hard error rather than a guess: a new operation in the
 * snapshot should be named deliberately in all four SDKs.
 */
const REQUEST_NAMES = {
  postKundli: 'KundliRequest',
  postKundliDasha: 'DashaRequest',
  postKundliVargas: 'VargasRequest',
  postKundliChalit: 'ChalitRequest',
  postKundliYogas: 'YogasRequest',
  postKundliShadbala: 'ShadbalaRequest',
  postKundliBhavaBala: 'BhavaBalaRequest',
  postKundliAshtakavarga: 'AshtakavargaRequest',
  postKundliGrahaDrishti: 'GrahaDrishtiRequest',
  postKundliMaitri: 'MaitriRequest',
  postKundliPace: 'PaceRequest',
  postKundliSpecialLagnas: 'SpecialLagnasRequest',
  postKundliTripataki: 'TripatakiRequest',
  postKundliSarvatobhadra: 'SarvatobhadraRequest',
  postKundliNakshatra28: 'Nakshatra28Request',
  postKundliSadeSati: 'SadeSatiRequest',
  postKundliEvents: 'EventsRequest',
  postKundliKotaChakra: 'KotaChakraRequest',
  postKundliChart: 'KundliChartRequest',
  postPanchang: 'PanchangRequest',
  postPanchangMuhurta: 'MuhurtaRequest',
  postPanchangMonth: 'PanchangMonthRequest',
  postEphemerisMonth: 'EphemerisMonthRequest',
  postCalendarVikramSamvat: 'VikramSamvatRequest',
  postJaiminiKarakas: 'JaiminiKarakasRequest',
  postJaiminiArudhaPadas: 'JaiminiArudhaPadasRequest',
  postJaiminiAspects: 'JaiminiAspectsRequest',
  postJaiminiKarakamsha: 'JaiminiKarakamshaRequest',
  postKpChart: 'KpChartRequest',
  postVarshphal: 'VarshphalRequest',
  postVarshphalBala: 'VarshphalBalaRequest',
  postVarshphalSahams: 'VarshphalSahamsRequest',
  postVarshphalYogas: 'VarshphalYogasRequest',
  postVarshphalDasha: 'VarshphalDashaRequest',
  postTransitNow: 'TransitNowRequest',
  postTransitScan: 'TransitScanRequest',
  postTransitEvents: 'TransitEventsRequest',
  postMatchAshtakoot: 'MatchAshtakootRequest',
  postMatchCompare: 'MatchCompareRequest',
  postMatchBatch: 'MatchBatchRequest',
  postReportsLagna: 'ReportLagnaRequest',
  postReportsNakshatra: 'ReportNakshatraRequest',
  postHoroscope: 'HoroscopeRequest',
  postReportsHouseLords: 'ReportHouseLordsRequest',
  postReportsGrahas: 'ReportGrahasRequest',
  postReportsYogas: 'ReportYogasRequest',
  postReportsVimshottari: 'ReportVimshottariRequest',
  postReportsVarshphal: 'ReportVarshphalRequest',
  postReportsLifeAreas: 'ReportLifeAreasRequest',
  postReportsKundli: 'ReportKundliRequest',
  postPdfKundli: 'PdfKundliRequest',
  postPdfMatch: 'PdfMatchRequest',
  postPdfVarshphal: 'PdfVarshphalRequest',
  postPdfPanchangMonth: 'PdfPanchangMonthRequest',
};

/** Names for the documents that are not `$ref`s to a named schema. */
const INLINE_DOCUMENT_NAMES = {
  getHealth: 'HealthDocument',
  getTimezone: 'TimezoneDocument',
  postMatchBatch: 'BatchDocument',
  getPlaces: 'PlacesDocument',
};

/**
 * Names for the `meta` members that are not a `$ref` either.
 *
 * `GET /v1/reference/{list}` and `GET /v1/timezone` report something narrower
 * than `Meta`: nothing was computed, so there is no ayanamsa and no timezone
 * to name.
 */
const INLINE_META_NAMES = {
  getReferenceList: 'ReferenceMeta',
  getTimezone: 'TimezoneMeta',
  getPlaces: 'PlacesMeta',
};

/**
 * Schemas whose own name is not used verbatim.
 *
 * Python could say `Error`, but Dart cannot, and the SDKs share class names —
 * so every SDK says `ErrorBody`.
 */
const SCHEMA_RENAMES = { Error: 'ErrorBody' };

/** Nested shapes worth a hand-picked name instead of a path-derived one. */
const NESTED_RENAMES = {
  ErrorBodyError: 'ErrorDetail',
  // `MaitriDocument` is a map of maps, so the path-derived name for the leaf
  // is `MaitriDocumentValueValue`, which says nothing.
  MaitriDocumentValueValue: 'MaitriRelation',
  // `{start, end}` — the muhurta windows of both panchang documents.
  DailyPanchangDocumentAbhijitMuhurta: 'TimeWindow',
  // One house system's cusps in `ChalitDocument`, which publishes four.
  ChalitDocumentEqual: 'ChalitHouses',
  // Pratyantardasha, sookshma and pran dasha (levels 3–5) nest one `children[]` deeper each; the path-derived
  // names grow a `ChildrenItem` per level and outrun the line length.
  DashaDocumentSystemsVimshottariPeriodsItemChildrenItemChildrenItem:
    'DashaVimshottariPratyantardasha',
  DashaVimshottariPratyantardashaChildrenItem: 'DashaVimshottariSookshma',
  DashaVimshottariSookshmaChildrenItem: 'DashaVimshottariPran',
  DashaDocumentSystemsCharaPeriodsItemChildrenItemChildrenItem: 'DashaCharaPratyantardasha',
  DashaCharaPratyantardashaChildrenItem: 'DashaCharaSookshma',
  DashaCharaSookshmaChildrenItem: 'DashaCharaPran',
  // `options.disclaimer` as an object: the astrologer the closing line names.
  CalculationOptionsDisclaimer: 'Disclaimer',
  // `{en?, hi?}` — every text of the report routes, and their `disclaimer`.
  ReadingLagnaDocumentLagna: 'ReadingLagna',
  ReadingLagnaEntry: 'ReadingEntry',
  ReadingEntryText: 'LocalizedText',
  ReadingNakshatraDocumentNakshatra: 'ReadingNakshatra',
  // One house of the house-lords reading: its sign, the lord, where the lord sits.
  ReadingHouseLordsDocumentHouseLordsItem: 'HouseLord',
  // The summaries (API 0.9.1): `{level, text}` overall, and `{area, level,
  // text}` per life area — the same two shapes in the horoscope and the
  // varshphal reading, whichever of the two the generator meets first.
  HoroscopeDocumentSummary: 'ReadingSummary',
  VarshphalReadingDocumentSummary: 'ReadingSummary',
  HoroscopeDocumentAreasItem: 'AreaSummary',
  VarshphalReadingDocumentAreasItem: 'AreaSummary',
  // One transit behind a horoscope: for the site, not the reader.
  HoroscopeDocumentBasisItem: 'HoroscopeTransit',
  // One graha of the grahas reading; one yoga of the yogas reading.
  ReadingGrahasDocumentGrahasItem: 'GrahaReading',
  ReadingYogasDocumentYogasItem: 'YogaReading',
  // One mahadasha of the Vimshottari reading, its antardashas, and the
  // houses it acts on.
  VimshottariReadingDocumentPeriodsItem: 'MahadashaReading',
  MahadashaReadingAntardashasItem: 'AntardashaReading',
  MahadashaReadingAreasItem: 'MahadashaArea',
  // One period (mudda dasha) of the varshphal year.
  VarshphalReadingDocumentMonthsItem: 'VarshphalPeriod',
  // One ingress or station of the year's transit calendar.
  TransitEventsDocumentEventsItem: 'TransitEvent',
  // The life-areas reading: its summary, one area, and a dasha period that
  // brings the area forward.
  LifeAreasDocumentSummary: 'LifeAreasSummary',
  LifeAreasDocumentAreasItem: 'LifeArea',
  LifeAreaPeriodsItem: 'LifeAreaPeriod',
  // The kundli report's parts. The gateway infers their schemas apart from
  // the parts' own routes, so they are not always the same shapes; they get
  // names of their own rather than the generated `KundliReportDocument…`.
  KundliReportDocumentGrahasItem: 'KundliReportGraha',
  KundliReportDocumentHouseLordsItem: 'KundliReportHouseLord',
  KundliReportDocumentLifeAreas: 'KundliReportLifeAreas',
  KundliReportDocumentVarshphal: 'KundliReportVarshphal',
  KundliReportDocumentVimshottari: 'KundliReportVimshottari',
  KundliReportVimshottariPeriodsItem: 'KundliReportMahadasha',
  PlacesDocumentPlacesItem: 'Place',
  // A PDF's own branding, the same object in all four PDF requests.
  PdfKundliRequestBranding: 'PdfBranding',
};

/**
 * Prose for the shapes the snapshot writes inline and therefore never
 * describes. Everything else takes its docstring from the schema.
 */
const DESCRIPTIONS = {
  Birth: [
    'A wall clock, a place, and at most one of `timezone` / `utc_offset`.',
    '',
    'Every birth-based operation takes the same object, so it is worth',
    'building once and passing everywhere. The "at most one zone" rule is the',
    "API's: sending both is a `400`.",
  ].join('\n'),
  CalculationOptions: [
    'Ayanamsa, label languages, engine pin and disclaimer.',
    '',
    'Every field is optional; the gateway applies its own defaults',
    '(`lahiri`, `en`) for the ones left out. The house system is not here:',
    'only the kundli PDF takes one, on `PdfKundliOptions`.',
  ].join('\n'),
  PdfKundliOptions: [
    "The kundli PDF's options: `CalculationOptions` plus `house_system`.",
    '',
    '`house_system` picks the bhava chalit the PDF prints (default',
    '`placidus`); every other route refuses it with a `400`.',
  ].join('\n'),
  'CalculationOptions.disclaimer': [
    'The closing line of the report routes: `"default"`, `"off"`, or a',
    '`Disclaimer` naming the astrologer to consult. No effect elsewhere.',
  ].join(' '),
  Disclaimer: 'The astrologer the closing line of a reading or horoscope names.',
  ReadingEntry: 'A reading: its text, keyed by language.',
  ReadingLagna: 'The lagna read, and its reading.',
  ReadingNakshatra: 'The janma nakshatra read, and its reading.',
  ReadingSummary:
    'The overall line of a summary report: its `level` and its text, keyed by language.',
  AreaSummary: [
    'One life area of a summary report: `area`, its `level` — `favourable`,',
    '`mixed` or `care` — and its text, keyed by language.',
  ].join('\n'),
  HoroscopeTransit: [
    'One graha in one sign behind a horoscope, for the part of the period it stays there.',
    '',
    '`entered` and `leaves` are the instants it changes sign inside the period,',
    'and `None` when it was already there, or stays, at the edge. For the site,',
    'not the reader.',
  ].join('\n'),
  GrahaReading: 'One graha of a birth chart: its sign and house, and what it says in each.',
  YogaReading: 'One yoga that forms in a birth chart: its code, the grahas in it and its reading.',
  MahadashaReading: [
    'One Vimshottari mahadasha: its lord and dates, its `level` and its text;',
    '`current` for the one running now.',
  ].join('\n'),
  Place: 'One place `GET /v1/places` found: everything a `Birth` needs besides the clock.',
  'CalculationOptions.language': [
    'The languages labels should come back in. Always a list here —',
    '`language=["en", "hi"]` — and a single language is written to the wire',
    'as the bare string the API documents.',
  ].join(' '),
};
DESCRIPTIONS['PdfKundliOptions.language'] = DESCRIPTIONS['CalculationOptions.language'];

/** `GET /v1/reference/{list}` rows are open by design — no class for them. */
const OPERATIONS_WITHOUT_DOCUMENT = new Set(['getReferenceList']);

// ---------------------------------------------------------------------------
// Names
// ---------------------------------------------------------------------------

/**
 * Names a field cannot take.
 *
 * Python's keywords, plus every name the generated class bodies use in an
 * annotation or define themselves: inside a class body a field called `list`
 * would shadow the builtin for every later annotation, which `mypy` rejects.
 */
const RESERVED = new Set([
  'False',
  'None',
  'True',
  'and',
  'as',
  'assert',
  'async',
  'await',
  'break',
  'class',
  'continue',
  'def',
  'del',
  'elif',
  'else',
  'except',
  'finally',
  'for',
  'from',
  'global',
  'if',
  'import',
  'in',
  'is',
  'lambda',
  'nonlocal',
  'not',
  'or',
  'pass',
  'raise',
  'return',
  'try',
  'while',
  'with',
  'yield',
  // Names the class bodies need to mean what they say.
  'self',
  'str',
  'int',
  'float',
  'bool',
  'list',
  'dict',
  'Any',
  'ClassVar',
  'Final',
  'Mapping',
  'LabelledId',
  'from_dict',
  'to_dict',
]);

/** `utc_offset` / `UtcOffset` / `utcOffset` → `['utc', 'offset']`. */
function words(name) {
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean);
}

function pascal(name) {
  return words(name)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join('');
}

/** The attribute a wire key becomes: the key itself wherever Python allows. */
function pyName(wire) {
  let name = /^[a-z_][a-z0-9_]*$/.test(wire)
    ? wire
    : words(wire)
        .map((w) => w.toLowerCase())
        .join('_');
  if (/^[0-9]/.test(name)) name = `n${name}`;
  return RESERVED.has(name) ? `${name}_` : name;
}

/** `whole_sign` → `WHOLE_SIGN`, the name a class constant goes by. */
function constantName(value) {
  return words(value)
    .map((w) => w.toUpperCase())
    .join('_');
}

// ---------------------------------------------------------------------------
// Python source helpers
// ---------------------------------------------------------------------------

/** A Python string literal. JSON's escapes are all valid Python escapes. */
function quote(text) {
  return JSON.stringify(String(text));
}

/** The line length in `pyproject.toml`, which `ruff check` enforces (E501). */
const WIDTH = 100;

/** `text` broken on spaces into lines of at most `width` characters. */
function wrap(text, width) {
  const out = [];
  let line = '';
  for (const word of text.split(' ')) {
    if (line === '') line = word;
    else if (`${line} ${word}`.length <= width) line = `${line} ${word}`;
    else {
      out.push(line);
      line = word;
    }
  }
  if (line !== '') out.push(line);
  return out;
}

/** A description as docstring lines: trimmed, wrapped, blank lines kept. */
function prose(text, indent) {
  if (!text) return [];
  const width = WIDTH - indent.length - 4;
  const out = [];
  for (const raw of String(text).trim().split('\n')) {
    const line = raw.replace(/\s+$/, '').replace(/\\/g, '\\\\').replace(/"""/g, '\\"\\"\\"');
    if (line === '') out.push('');
    else out.push(...wrap(line, width));
  }
  return out;
}

/** A docstring, one line when it fits, otherwise opening and closing alone. */
function docstring(lines, indent) {
  if (lines.length === 0) return [];
  const safe = [...lines];
  // A docstring may not end in a quote: `""""` would close it early.
  if (safe[safe.length - 1].endsWith('"')) safe[safe.length - 1] += ' ';
  if (safe.length === 1 && `${indent}"""${safe[0]}"""`.length <= WIDTH) {
    return [`${indent}"""${safe[0]}"""`];
  }
  return [
    `${indent}"""${safe[0]}`,
    ...safe.slice(1).map((line) => (line ? `${indent}${line}` : '')),
    `${indent}"""`,
  ];
}

// ---------------------------------------------------------------------------
// Structural identity
// ---------------------------------------------------------------------------

/**
 * A schema reduced to the part of it Python can see.
 *
 * `birth` and `options` are written out inline in 35-odd request bodies, and
 * two of those copies differ only in a `default` (`KP` defaults the ayanamsa
 * to `krishnamurti`). Validation keywords, defaults and prose change nothing
 * about the generated class, so they are dropped before comparing: what is
 * left is the shape, and equal shapes share one class.
 */
function shapeKey(schema) {
  // At the root, `{"type": ["null", "object"]}` and `{"type": "object"}` are
  // the same class: whether the *field* may be null is the field's business.
  return JSON.stringify(shapeOf(schema, true));
}

function shapeOf(schema, root = false) {
  if (!schema || typeof schema !== 'object') return schema ?? null;
  if (schema.$ref) return { $ref: schema.$ref };
  const out = {};
  if (schema.type !== undefined) {
    let declared = Array.isArray(schema.type) ? [...schema.type].sort() : schema.type;
    if (root && Array.isArray(declared)) {
      const real = declared.filter((t) => t !== 'null');
      declared = real.length === 1 ? real[0] : real.length === 0 ? 'null' : real;
    }
    out.type = declared;
  }
  if (schema.anyOf) out.anyOf = schema.anyOf.map((branch) => shapeOf(branch));
  if (schema.properties) {
    out.properties = {};
    for (const key of Object.keys(schema.properties).sort()) {
      out.properties[key] = shapeOf(schema.properties[key]);
    }
  }
  if (schema.required) out.required = [...schema.required].sort();
  if (schema.items) out.items = shapeOf(schema.items);
  if (schema.additionalProperties === true) out.additionalProperties = true;
  else if (schema.additionalProperties && typeof schema.additionalProperties === 'object') {
    out.additionalProperties = shapeOf(schema.additionalProperties);
  }
  return out;
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * A resolved Python type.
 *
 * `kind` drives the `from_dict` / `to_dict` expressions; `render` is what the
 * field is annotated as. `nullable` is tracked separately so a
 * `list[T] | None` knows its element type is not itself optional.
 */
function type(kind, extra = {}) {
  return { kind, nullable: false, ...extra };
}

function render(t) {
  let base;
  switch (t.kind) {
    case 'string':
      base = 'str';
      break;
    case 'int':
      base = 'int';
      break;
    case 'double':
      base = 'float';
      break;
    case 'bool':
      base = 'bool';
      break;
    case 'stringList':
      base = 'list[str]';
      break;
    case 'stringOrClass':
      base = `str | ${t.name}`;
      break;
    case 'class':
      base = t.name;
      break;
    case 'list':
      base = `list[${render(t.of)}]`;
      break;
    case 'map':
      base = `dict[str, ${render(t.of)}]`;
      break;
    case 'json':
      base = 'dict[str, Any]';
      break;
    case 'any':
      return 'Any';
    default:
      throw new Error(`unknown kind ${t.kind}`);
  }
  return t.nullable ? `${base} | None` : base;
}

/** True when a value of `t` is already JSON and needs no mapping either way. */
function isPlain(t) {
  return ['string', 'int', 'double', 'bool', 'json', 'any'].includes(t.kind);
}

/** The expression that reads `expr` (an `Any`) as a non-None `t`. */
function readNonNull(t, expr, depth) {
  switch (t.kind) {
    case 'string':
      return `as_str(${expr})`;
    case 'int':
      return `as_int(${expr})`;
    case 'double':
      return `as_float(${expr})`;
    case 'bool':
      return `as_bool(${expr})`;
    case 'stringList':
      return `as_str_list(${expr})`;
    case 'stringOrClass':
      return `${expr} if isinstance(${expr}, str) else ${t.name}.from_dict(as_dict(${expr}))`;
    case 'class':
      return `${t.name}.from_dict(as_dict(${expr}))`;
    case 'json':
      return `as_dict(${expr})`;
    case 'any':
      return expr;
    case 'list': {
      const e = `e${depth}`;
      const inner = read(t.of, e, depth + 1);
      return inner === e ? `as_list(${expr})` : `[${inner} for ${e} in as_list(${expr})]`;
    }
    case 'map': {
      const k = `k${depth}`;
      const v = `v${depth}`;
      const inner = read(t.of, v, depth + 1);
      return inner === v
        ? `as_dict(${expr})`
        : `{${k}: ${inner} for ${k}, ${v} in as_dict(${expr}).items()}`;
    }
    default:
      throw new Error(`unknown kind ${t.kind}`);
  }
}

/** The expression that reads `expr` as `t`, optionality included. */
function read(t, expr, depth = 0) {
  if (!t.nullable) return readNonNull(t, expr, depth);
  if (t.kind === 'any') return expr;
  const simple = {
    string: 'as_str_or_none',
    int: 'as_int_or_none',
    double: 'as_float_or_none',
    bool: 'as_bool_or_none',
    json: 'as_dict_or_none',
  };
  if (simple[t.kind]) return `${simple[t.kind]}(${expr})`;
  const inner = readNonNull(t, expr, depth);
  return `None if ${expr} is None else ${t.kind === 'stringOrClass' ? `(${inner})` : inner}`;
}

/** The expression that turns `expr`, a non-None `t`, back into JSON. */
function writeNonNull(t, expr, depth) {
  switch (t.kind) {
    case 'class':
      return `${expr}.to_dict()`;
    case 'stringList':
      // A single language goes out as the string the gateway documents.
      return `${expr}[0] if len(${expr}) == 1 else list(${expr})`;
    case 'stringOrClass':
      return `${expr} if isinstance(${expr}, str) else ${expr}.to_dict()`;
    case 'list': {
      if (isPlain(t.of)) return `list(${expr})`;
      const e = `e${depth}`;
      return `[${write(t.of, e, depth + 1)} for ${e} in ${expr}]`;
    }
    case 'map': {
      if (isPlain(t.of)) return `dict(${expr})`;
      const k = `k${depth}`;
      const v = `v${depth}`;
      return `{${k}: ${write(t.of, v, depth + 1)} for ${k}, ${v} in ${expr}.items()}`;
    }
    default:
      return expr;
  }
}

function write(t, expr, depth = 0) {
  if (!t.nullable || isPlain(t)) return writeNonNull(t, expr, depth);
  const inner = writeNonNull(t, expr, depth);
  const wrapped = t.kind === 'stringList' || t.kind === 'stringOrClass';
  return `None if ${expr} is None else ${wrapped ? `(${inner})` : inner}`;
}

// ---------------------------------------------------------------------------
// The model graph
// ---------------------------------------------------------------------------

const doc = JSON.parse(await readFile(schemaFile, 'utf8'));
const pyproject = await readFile(join(packageDir, 'pyproject.toml'), 'utf8');
// The `[project]` table only: its `version` is the package's, and other
// tables (a tool's) may have a `version` key of their own.
const projectTable = pyproject.split(/^\[project\]\s*$/m)[1]?.split(/^\[/m)[0] ?? '';
const sdkVersion = /^version\s*=\s*"([^"]+)"\s*$/m.exec(projectTable)?.[1];
if (!sdkVersion) throw new Error('pyproject.toml has no [project] version');

/** name → { name, description, origin, fields } for every class but `LabelledId`. */
const classes = new Map();
/** shapeKey → class name, so one shape is one class. */
const shapes = new Map();
/** Constructs the generator could not represent exactly, reported at the end. */
const fallbacks = [];

function refName(ref) {
  const raw = ref.replace('#/components/schemas/', '');
  return SCHEMA_RENAMES[raw] ?? raw;
}

/**
 * Resolve one schema to a Python type, defining classes as it goes.
 *
 * `hint` is the name a class would get if this schema turns out to need one:
 * the owning class plus the property, so `KundliDocument.birth` is
 * `KundliDocumentBirth` and the value type of its `positions` map is
 * `KundliDocumentPositionsValue`.
 */
function resolve(schema, hint, origin) {
  if (!schema || typeof schema !== 'object') return type('any');
  if (schema.$ref) return type('class', { name: refName(schema.$ref) });

  if (schema.anyOf) return resolveAnyOf(schema, hint, origin);

  const listed = Array.isArray(schema.type) ? schema.type : schema.type ? [schema.type] : [];
  const nullable = listed.includes('null');
  const rest = listed.filter((t) => t !== 'null');

  if (rest.length === 0 && nullable) {
    // `{"type": "null"}`: the engine always answers null here (choghadiya's
    // `planet`). There is no Python type for "always None" worth having, so
    // the field is an `Any` the caller can ignore.
    fallbacks.push(`${origin}: \`type: "null"\` → Any`);
    return type('any', { nullable: true });
  }
  if (rest.length > 1) {
    fallbacks.push(`${origin}: \`type: ${JSON.stringify(listed)}\` → Any`);
    return type('any', { nullable: true });
  }

  const base = rest[0] ?? (schema.properties ? 'object' : schema.items ? 'array' : undefined);
  let resolved;
  switch (base) {
    case 'string':
      resolved = type('string');
      break;
    case 'integer':
      resolved = type('int');
      break;
    case 'number':
      // `number` is `float`, except where the schema enumerates whole
      // numbers (`levels: 1 | 2 | 3 | 4 | 5`) and an int reads better on the wire.
      resolved = type(allIntegerEnum(schema) ? 'int' : 'double');
      break;
    case 'boolean':
      resolved = type('bool');
      break;
    case 'array':
      resolved = type('list', { of: resolve(schema.items, `${hint}Item`, `${origin}[]`) });
      break;
    case 'object':
      resolved = resolveObject(schema, hint, origin);
      break;
    default:
      fallbacks.push(`${origin}: no \`type\` → Any`);
      resolved = type('any', { nullable: true });
  }
  return nullable ? { ...resolved, nullable: true } : resolved;
}

function allIntegerEnum(schema) {
  return Array.isArray(schema.enum) && schema.enum.every((v) => Number.isInteger(v));
}

function resolveObject(schema, hint, origin) {
  if (schema.properties) return type('class', { name: defineClass(schema, hint, origin) });
  const extra = schema.additionalProperties;
  if (extra && typeof extra === 'object') {
    return type('map', { of: resolve(extra, `${hint}Value`, `${origin}{}`) });
  }
  // `additionalProperties: true`, or no properties at all: an open row.
  return type('json');
}

function resolveAnyOf(schema, hint, origin) {
  const branches = schema.anyOf;
  const isNull = (b) =>
    b.type === 'null' ||
    (Array.isArray(b.type) && !b.type.includes('object') && b.type.every((t) => t === 'null'));
  const nullable =
    branches.some(isNull) || branches.some((b) => Array.isArray(b.type) && b.type.includes('null'));
  const real = branches.filter((b) => !isNull(b));

  // `options.language`: `'en'` or `['en', 'hi']` on the wire. Callers get one
  // type — a list — and a single-element list goes out as the bare string.
  const stringOrList =
    real.length === 2 &&
    real.some((b) => b.type === 'string') &&
    real.some((b) => b.type === 'array' && b.items?.type === 'string');
  if (stringOrList) return type('stringList', { nullable });

  if (real.length === 1) return { ...resolve(real[0], hint, origin), nullable: true };

  // `levels: 1 | 2 | 3 | 4 | 5` arrives as five single-value `number` branches.
  if (real.length > 1 && real.every((b) => b.type === 'number' && allIntegerEnum(b))) {
    return type('int', { nullable });
  }
  if (real.length > 1 && real.every((b) => b.type === real[0].type && !b.properties)) {
    return { ...resolve(real[0], hint, origin), nullable };
  }

  // `options.disclaimer`: `'default'`, `'off'`, or `{name, url?}`. Callers
  // pass either; the class is written out as its dict, the string as itself.
  const stringBranch = real.find((b) => b.type === 'string');
  const objectBranch = real.find((b) => b.type === 'object' && b.properties);
  if (real.length === 2 && stringBranch && objectBranch) {
    const inner = resolve(objectBranch, hint, origin);
    return type('stringOrClass', { name: inner.name, nullable });
  }

  fallbacks.push(`${origin}: \`anyOf\` of ${real.length} unrelated shapes → Any`);
  return type('any', { nullable: true });
}

/**
 * Define (or reuse) the class for an object schema and answer its name.
 *
 * Equal shapes share a class, which is what keeps `Birth` and
 * `CalculationOptions` single classes instead of 35 copies apiece.
 */
function defineClass(schema, preferred, origin) {
  const key = shapeKey(schema);
  const existing = shapes.get(key);
  if (existing) return existing;

  let name = NESTED_RENAMES[preferred] ?? preferred;
  if (classes.has(name)) {
    let n = 2;
    while (classes.has(`${name}${n}`)) n += 1;
    fallbacks.push(`${origin}: name ${name} was taken → ${name}${n}`);
    name = `${name}${n}`;
  }

  const entry = {
    name,
    description: DESCRIPTIONS[name] ?? schema.description,
    origin,
    fields: [],
  };
  classes.set(name, entry);
  shapes.set(key, name);

  if (!schema.properties) {
    // A document that is a bare map (`MaitriDocument` is planet → planet →
    // relation). A dict has no place to hang `from_dict`, so the class wraps
    // the map and subscripts through to it; `to_dict()` still answers the
    // map itself, so the wire shape is unchanged.
    entry.valueType = resolve(
      schema.additionalProperties && typeof schema.additionalProperties === 'object'
        ? schema.additionalProperties
        : {},
      `${name}Value`,
      `${origin}{}`,
    );
    return name;
  }

  const required = new Set(schema.required ?? []);
  const used = new Map();
  for (const [wire, propSchema] of Object.entries(schema.properties)) {
    let field = pyName(wire);
    if (used.has(field)) {
      fallbacks.push(`${name}: \`${wire}\` and \`${used.get(field)}\` both become ${field}`);
      field = `${field}_${pyName(wire)}`;
    }
    used.set(field, wire);
    const fieldType = resolve(propSchema, name + pascal(wire), `${name}.${wire}`);
    entry.fields.push({
      wire,
      name: field,
      description: DESCRIPTIONS[`${name}.${wire}`] ?? propSchema.description,
      // Anything the schema does not require, and anything it requires but
      // allows to be null, is optional here: the gateway omits keys it has
      // nothing to say about.
      type: { ...fieldType, nullable: fieldType.nullable || !required.has(wire) },
    });
  }
  // A dataclass will not take a field without a default after one with, so
  // the fields the schema requires come first, each group in schema order.
  // Callers use keyword arguments, so the order is `__init__`'s business.
  entry.fields.sort((a, b) => Number(a.type.nullable) - Number(b.type.nullable));
  return name;
}

// ---------------------------------------------------------------------------
// Walk the document
// ---------------------------------------------------------------------------

const schemas = doc.components.schemas;
const bodyOf = (op) => op.requestBody?.content?.['application/json']?.schema;
const okOf = (op) => op.responses?.['200']?.content?.['application/json']?.schema;

// `birth` and `options` first, so the 35 inline copies find them already
// defined and every request refers to the same two classes.
const kundliBody = bodyOf(doc.paths['/v1/kundli'].post);
defineClass(kundliBody.properties.birth, 'Birth', 'POST /v1/kundli birth');
defineClass(kundliBody.properties.options, 'CalculationOptions', 'POST /v1/kundli options');
// The kundli PDF's options add `house_system` (the chalit it prints), which no
// other route takes; after `CalculationOptions`, so its `disclaimer` object
// finds `Disclaimer` already defined.
const pdfKundliBody = bodyOf(doc.paths['/v1/pdf/kundli'].post);
defineClass(pdfKundliBody.properties.options, 'PdfKundliOptions', 'POST /v1/pdf/kundli options');

// A `/v1/panchang/month` day carries the same `{amanta, purnimanta}` pair as
// `masa` that `/v1/calendar/vikram-samvat` answers, and `PanchangMonthDocument`
// comes first; name the pair after the document so the day reuses it.
defineClass(
  schemas.VikramSamvatDocument,
  'VikramSamvatDocument',
  '#/components/schemas/VikramSamvatDocument',
);

for (const [rawName, schema] of Object.entries(schemas)) {
  if (rawName === 'LabelledId') continue; // its own file, written out below
  defineClass(schema, SCHEMA_RENAMES[rawName] ?? rawName, `#/components/schemas/${rawName}`);
}

const operations = [];
for (const [path, item] of Object.entries(doc.paths)) {
  for (const [method, op] of Object.entries(item)) {
    if (!op.operationId) continue;
    const id = op.operationId;
    const body = bodyOf(op);
    let requestType = null;
    if (body) {
      const name = REQUEST_NAMES[id];
      if (!name) throw new Error(`${id} has a request body but no name in REQUEST_NAMES`);
      requestType = defineClass(body, name, `${method.toUpperCase()} ${path} body`);
    }

    let documentType = null;
    const ok = okOf(op);
    if (ok && !OPERATIONS_WITHOUT_DOCUMENT.has(id)) {
      const data = ok.properties?.data ?? ok;
      const name = INLINE_DOCUMENT_NAMES[id];
      documentType = data.$ref
        ? refName(data.$ref)
        : defineClass(
            data,
            name ?? `${pascal(id)}Document`,
            `${method.toUpperCase()} ${path} data`,
          );
    }
    const metaName = INLINE_META_NAMES[id];
    if (metaName && ok?.properties?.meta && !ok.properties.meta.$ref) {
      defineClass(ok.properties.meta, metaName, `${method.toUpperCase()} ${path} meta`);
    }

    operations.push({
      id,
      method: method.toUpperCase(),
      path,
      tag: op.tags?.[0] ?? '',
      requestType,
      documentType,
    });
  }
}

// ---------------------------------------------------------------------------
// Emit
// ---------------------------------------------------------------------------

const sortedClasses = [...classes.values()].sort((a, b) =>
  a.name < b.name ? -1 : a.name > b.name ? 1 : 0,
);

function classDocstring(entry) {
  const lines = prose(entry.description, '    ');
  if (lines.length > 0) lines.push('');
  lines.push(...prose(`Wire shape: \`${entry.origin}\`.`, '    '));
  return docstring(lines, '    ');
}

function emitClass(entry) {
  if (entry.valueType) return emitMapClass(entry);

  const out = ['@dataclass(frozen=True, slots=True)', `class ${entry.name}:`];
  out.push(...classDocstring(entry));
  out.push('');

  const renamed = entry.fields.filter((f) => f.name !== f.wire);
  if (renamed.length > 0) {
    out.push('    _WIRE: ClassVar[dict[str, str]] = {');
    for (const f of renamed) out.push(`        ${quote(f.name)}: ${quote(f.wire)},`);
    out.push('    }');
    out.push('    """Attributes whose wire key is not their own name."""');
    out.push('');
  }

  for (const f of entry.fields) {
    out.push(`    ${f.name}: ${render(f.type)}${f.type.nullable ? ' = None' : ''}`);
    const lines = prose(f.description, '    ');
    if (f.name !== f.wire) {
      if (lines.length > 0) lines.push('');
      lines.push(`Wire key: \`${f.wire}\`.`);
    }
    out.push(...docstring(lines, '    '));
  }
  if (entry.fields.length > 0) out.push('');

  out.push('    @classmethod');
  out.push(`    def from_dict(cls, data: Mapping[str, Any]) -> ${entry.name}:`);
  out.push('        """Read the wire shape, as `json.loads` returns it."""');
  if (entry.fields.length === 0) {
    out.push('        del data');
    out.push('        return cls()');
  } else {
    out.push('        return cls(');
    for (const f of entry.fields) {
      out.push(`            ${f.name}=${read(f.type, `data.get(${quote(f.wire)})`)},`);
    }
    out.push('        )');
  }
  out.push('');

  out.push('    def to_dict(self) -> dict[str, Any]:');
  out.push('        """This value as JSON, with every `None` left out."""');
  out.push('        out: dict[str, Any] = {}');
  for (const f of entry.fields) {
    const self = `self.${f.name}`;
    const target = `out[${quote(f.wire)}]`;
    if (!f.type.nullable) {
      out.push(`        ${target} = ${writeNonNull(f.type, self, 0)}`);
    } else {
      out.push(`        if ${self} is not None:`);
      out.push(`            ${target} = ${writeNonNull({ ...f.type, nullable: false }, self, 0)}`);
    }
  }
  out.push('        return out');
  return out.join('\n');
}

/** A document that is a bare map: the class wraps it and subscripts through. */
function emitMapClass(entry) {
  const value = render(entry.valueType);
  const optional =
    entry.valueType.nullable || entry.valueType.kind === 'any' ? value : `${value} | None`;
  const out = ['@dataclass(frozen=True, slots=True)', `class ${entry.name}:`];
  out.push(...classDocstring(entry));
  out.push('');
  out.push(`    values: dict[str, ${value}]`);
  out.push('    """The document itself, keyed as the API keys it."""');
  out.push('');
  out.push(`    def __getitem__(self, key: str) -> ${value}:`);
  out.push('        """The entry under `key`; `KeyError` when the API left it out."""');
  out.push('        return self.values[key]');
  out.push('');
  out.push(`    def get(self, key: str) -> ${optional}:`);
  out.push('        """The entry under `key`, or `None` when the API left it out."""');
  out.push('        return self.values.get(key)');
  out.push('');
  out.push('    @classmethod');
  out.push(`    def from_dict(cls, data: Mapping[str, Any]) -> ${entry.name}:`);
  out.push('        """Read the wire shape, as `json.loads` returns it."""');
  out.push(`        return cls({k: ${read(entry.valueType, 'v')} for k, v in data.items()})`);
  out.push('');
  out.push('    def to_dict(self) -> dict[str, Any]:');
  out.push('        """This value as JSON: the map itself."""');
  out.push(`        return {k: ${write(entry.valueType, 'v', 1)} for k, v in self.values.items()}`);
  return out.join('\n');
}

/**
 * A holder of the string constants an enum property accepts.
 *
 * Enums stay `str` on the fields themselves — the gateway adds values between
 * SDK releases and an `enum.Enum` would turn that into a crash — but the
 * values it lists today are worth spelling once so callers can autocomplete
 * them instead of quoting a slug from the docs.
 */
function emitConstants(name, description, values) {
  const out = [`class ${name}:`, ...docstring(prose(description, '    '), '    '), ''];
  for (const value of values) {
    out.push(`    ${constantName(value)}: Final = ${quote(value)}`);
  }
  out.push(`    VALUES: Final[tuple[str, ...]] = (${values.map(quote).join(', ')},)`);
  out.push('    """Every value the snapshot lists, in its order."""');
  return out.join('\n');
}

const jsonPy = `${HEADER(
  "Cast helpers. `json.loads` answers `Any`; these turn it into the types the\nmodels declare, and put a readable message on a malformed payload instead of\nletting a wrong type travel into the caller's code.",
)}
from __future__ import annotations

from typing import Any


class KaaljyotiFormatError(ValueError):
    """A payload does not have the shape the schema promised."""

    def __init__(self, wanted: str, value: object) -> None:
        self.wanted = wanted
        """The type the schema calls for."""
        self.value = value
        """The value that arrived instead."""
        got = "None" if value is None else f"{type(value).__name__} ({value!r:.60})"
        super().__init__(f"expected {wanted}, got {got}")


def as_dict(value: object) -> dict[str, Any]:
    """\`value\` as a JSON object."""
    if isinstance(value, dict):
        return value
    raise KaaljyotiFormatError("an object", value)


def as_list(value: object) -> list[Any]:
    """\`value\` as a JSON array."""
    if isinstance(value, list):
        return value
    raise KaaljyotiFormatError("an array", value)


def as_str(value: object) -> str:
    """\`value\` as a string."""
    if isinstance(value, str):
        return value
    raise KaaljyotiFormatError("a string", value)


def as_int(value: object) -> int:
    """\`value\` as an integer, accepting a float with nothing after the point."""
    if isinstance(value, bool):
        raise KaaljyotiFormatError("an integer", value)
    if isinstance(value, int):
        return value
    if isinstance(value, float) and value.is_integer():
        return int(value)
    raise KaaljyotiFormatError("an integer", value)


def as_float(value: object) -> float:
    """\`value\` as a float, accepting the integers JSON writes for whole numbers."""
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return float(value)
    raise KaaljyotiFormatError("a number", value)


def as_bool(value: object) -> bool:
    """\`value\` as a boolean."""
    if isinstance(value, bool):
        return value
    raise KaaljyotiFormatError("a boolean", value)


def as_str_list(value: object) -> list[str]:
    """\`value\` as the SDK's list-of-languages shape.

    The API writes a lone language as a bare string and several as an array.
    """
    if isinstance(value, str):
        return [value]
    return [as_str(item) for item in as_list(value)]


def as_dict_or_none(value: object) -> dict[str, Any] | None:
    """\`value\` as a JSON object, or \`None\`."""
    return None if value is None else as_dict(value)


def as_list_or_none(value: object) -> list[Any] | None:
    """\`value\` as a JSON array, or \`None\`."""
    return None if value is None else as_list(value)


def as_str_or_none(value: object) -> str | None:
    """\`value\` as a string, or \`None\`."""
    return None if value is None else as_str(value)


def as_int_or_none(value: object) -> int | None:
    """\`value\` as an integer, or \`None\`."""
    return None if value is None else as_int(value)


def as_float_or_none(value: object) -> float | None:
    """\`value\` as a float, or \`None\`."""
    return None if value is None else as_float(value)


def as_bool_or_none(value: object) -> bool | None:
    """\`value\` as a boolean, or \`None\`."""
    return None if value is None else as_bool(value)
`;

const labelled = schemas.LabelledId;
const labelledPy = `${HEADER('`LabelledId`, the shape every named id in every document shares.')}
from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from ._json import as_dict, as_str


@dataclass(frozen=True, slots=True)
class LabelledId:
${docstring([...prose(labelled.description, '    '), '', 'Wire shape: `#/components/schemas/LabelledId`.'], '    ').join('\n')}

    id: str
${docstring(prose(labelled.properties.id.description, '    '), '    ').join('\n')}
    name: str
${docstring(prose(labelled.properties.name.description, '    '), '    ').join('\n')}
    names: dict[str, str] | None = None
${docstring(prose(labelled.properties.names.description, '    '), '    ').join('\n')}

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> LabelledId:
        """Read an \`{id, name, names?}\` object."""
        names = data.get("names")
        return cls(
            id=as_str(data.get("id")),
            name=as_str(data.get("name")),
            names=None if names is None else {k: as_str(v) for k, v in as_dict(names).items()},
        )

    def to_dict(self) -> dict[str, Any]:
        """This value as JSON, with every \`None\` left out."""
        out: dict[str, Any] = {"id": self.id, "name": self.name}
        if self.names is not None:
            out["names"] = dict(self.names)
        return out

    def __str__(self) -> str:
        return self.name
`;

const helpersUsed = [
  'as_bool',
  'as_bool_or_none',
  'as_dict',
  'as_dict_or_none',
  'as_float',
  'as_float_or_none',
  'as_int',
  'as_int_or_none',
  'as_list',
  'as_str',
  'as_str_list',
  'as_str_or_none',
];
const modelBodies = [
  emitConstants(
    'Ayanamsa',
    'The ayanamsas `CalculationOptions.ayanamsa` accepts.',
    kundliBody.properties.options.properties.ayanamsa.enum,
  ),
  emitConstants(
    'HouseSystem',
    'The house systems `PdfKundliOptions.house_system` accepts.',
    pdfKundliBody.properties.options.properties.house_system.enum,
  ),
  emitConstants(
    'Varga',
    'The divisional charts `KundliChartRequest.varga` and `VargasRequest.vargas` accept.',
    bodyOf(doc.paths['/v1/kundli/chart'].post).properties.varga.enum,
  ),
  emitConstants(
    'ChartStyle',
    'The styles `KundliChartRequest.style` accepts.',
    bodyOf(doc.paths['/v1/kundli/chart'].post).properties.style.enum,
  ),
  ...sortedClasses.map(emitClass),
];
const modelSource = modelBodies.join('\n\n\n');
const importedHelpers = helpersUsed.filter((h) => new RegExp(`\\b${h}\\(`).test(modelSource));

const modelsPy = `${HEADER(
  'Every request body, every answer document, and the anonymous objects nested\ninside them. Classes are alphabetical; `LabelledId` has its own module.',
)}
from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any, ClassVar, Final

from ._json import ${importedHelpers.join(', ')}
from .labelled_id import LabelledId


${modelSource}
`;

const operationsPy = `${HEADER(
  'The operation table: what the client calls and what the contract test walks.',
)}
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class Operation:
    """One operation of the Kaal Jyoti API, as \`openapi/openapi.json\` describes it."""

    id: str
    """The \`operationId\` from the snapshot, e.g. \`postKundliDasha\`."""
    method: str
    """The HTTP verb, upper case."""
    path: str
    """The path, with its \`{list}\` placeholders intact."""
    tag: str
    """The tag the operation is grouped under, which is the client namespace."""
    request_type: str | None = None
    """The request class name, or \`None\` when the operation takes no JSON body."""
    document_type: str | None = None
    """The \`data\` class name, or \`None\` when the answer has no named shape."""

    def __str__(self) -> str:
        return f"{self.method} {self.path} ({self.id})"


OPERATIONS: tuple[Operation, ...] = (
${operations
  .map((op) => {
    const args = [
      `id=${quote(op.id)}`,
      `method=${quote(op.method)}`,
      `path=${quote(op.path)}`,
      `tag=${quote(op.tag)}`,
    ];
    if (op.requestType) args.push(`request_type=${quote(op.requestType)}`);
    if (op.documentType) args.push(`document_type=${quote(op.documentType)}`);
    return `    Operation(${args.join(', ')}),`;
  })
  .join('\n')}
)
"""Every operation in the snapshot, in the order the document lists them."""

_BY_ID: dict[str, Operation] = {op.id: op for op in OPERATIONS}


def operation(id: str) -> Operation:
    """The operation whose \`operationId\` is \`id\`; \`KeyError\` when there is none."""
    return _BY_ID[id]
`;

const versionPy = `${HEADER('The two versions the client reports and the contract test pins.')}
from __future__ import annotations

from typing import Final

SDK_VERSION: Final = ${quote(sdkVersion)}
"""The version of this package, from \`pyproject.toml\`.

Sent as \`X-KJ-Client: sdk-python/${sdkVersion}\`.
"""

OPENAPI_VERSION: Final = ${quote(doc.info.version)}
"""The \`info.version\` of the OpenAPI snapshot these models were built from."""
`;

const CONSTANT_HOLDERS = ['Ayanamsa', 'ChartStyle', 'HouseSystem', 'Varga'];
const exported = [...CONSTANT_HOLDERS, ...sortedClasses.map((c) => c.name)].sort();
const initPy = `${HEADER('Every generated public name, for `kaaljyoti/__init__.py` to re-export.')}
from ._json import KaaljyotiFormatError
from .labelled_id import LabelledId
from .models import (
${exported.map((name) => `    ${name},`).join('\n')}
)
from .operations import OPERATIONS, Operation, operation
from .version import OPENAPI_VERSION, SDK_VERSION

__all__ = [
${[
  'KaaljyotiFormatError',
  'LabelledId',
  'OPENAPI_VERSION',
  'OPERATIONS',
  'Operation',
  'SDK_VERSION',
  'operation',
  ...exported,
]
  .sort()
  .map((name) => `    ${quote(name)},`)
  .join('\n')}
]
`;

const files = {
  '__init__.py': initPy,
  '_json.py': jsonPy,
  'labelled_id.py': labelledPy,
  'models.py': modelsPy,
  'operations.py': operationsPy,
  'version.py': versionPy,
};

// ---------------------------------------------------------------------------
// Write, format, compare
// ---------------------------------------------------------------------------

function run(command, args, cwd) {
  return new Promise((resolve_, reject) => {
    const child = spawn(command, args, { cwd, stdio: ['inherit', 'ignore', 'inherit'] });
    child.on('error', reject);
    child.on('close', (code) =>
      code === 0 ? resolve_() : reject(new Error(`${command} ${args.join(' ')} exited ${code}`)),
    );
  });
}

/**
 * Write every file into `rel` and format it, inside the package so ruff reads
 * the package's `pyproject.toml`: format, fix what `ruff check` can (import
 * order), and format again so the fixes are laid out the same way.
 */
async function writeAll(rel) {
  const dir = join(packageDir, rel);
  await mkdir(dir, { recursive: true });
  for (const [name, source] of Object.entries(files)) {
    await writeFile(join(dir, name), source);
  }
  await run(ruff, ['format', '--quiet', rel], packageDir);
  await run(ruff, ['check', '--fix', '--quiet', rel], packageDir);
  await run(ruff, ['format', '--quiet', rel], packageDir);
}

const check = process.argv.includes('--check');

if (check) {
  await rm(checkDir, { recursive: true, force: true });
  const differ = [];
  try {
    await writeAll(checkRel);
    for (const name of Object.keys(files)) {
      const wanted = await readFile(join(checkDir, name));
      const current = await readFile(join(outDir, name)).catch(() => null);
      if (current === null) differ.push(`${name} (missing)`);
      else if (!current.equals(wanted)) differ.push(name);
    }
    const extra = (await readdir(outDir).catch(() => [])).filter(
      (n) => n.endsWith('.py') && !(n in files),
    );
    for (const name of extra) differ.push(`${name} (not generated any more)`);
  } finally {
    await rm(checkDir, { recursive: true, force: true });
  }

  if (differ.length > 0) {
    console.error(
      `${outRel} is out of date with openapi/openapi.json:\n` +
        differ.map((name) => `  - ${name}`).join('\n') +
        `\nRun: pnpm --filter sdk-python run gen`,
    );
    process.exit(1);
  }
  console.log(`${outRel} is current (${Object.keys(files).length} files).`);
} else {
  await writeAll(outRel);
  console.log(
    `Wrote ${Object.keys(files).length} files, ${classes.size + 1} classes ` +
      `(+${CONSTANT_HOLDERS.length} constant holders), ${operations.length} operations from openapi ${doc.info.version}.`,
  );
  if (fallbacks.length > 0) {
    console.log('Constructs with no exact Python shape:');
    for (const line of [...new Set(fallbacks)]) console.log(`  - ${line}`);
  }
}
