/**
 * Builds the shippable plugin directory.
 *
 * wordpress.org forbids loading executable code from another server, so the
 * widget bundle and the PHP SDK are copied into `kaaljyoti/` rather than
 * fetched at runtime or installed with Composer (design decision 1). Both
 * copies are build outputs: they are gitignored, and this script is the only
 * thing that writes them. The bundle is minified, so its readable source and
 * build go in too, as `widgets-src/` (WordPress.org's guideline 4).
 *
 *   node tool/build.mjs          copy the bundle, its source and the SDK in
 *   node tool/build.mjs --zip    …and write dist/kaaljyoti.zip
 */

import { execFileSync } from 'node:child_process';
import { cp, mkdir, readFile, readdir, rm, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const pluginRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = path.resolve(pluginRoot, '..', '..');
const shipped = path.join(pluginRoot, 'kaaljyoti');

const widgetDist = path.join(repoRoot, 'packages', 'widgets', 'dist');
const widgetManifest = path.join(widgetDist, 'cdn-files.json');
const sdkSource = path.join(repoRoot, 'packages', 'sdk-php', 'src');
const sdkPackageJson = path.join(repoRoot, 'packages', 'sdk-php', 'package.json');
const sdkComposerJson = path.join(repoRoot, 'packages', 'sdk-php', 'composer.json');

const widgetPackage = path.join(repoRoot, 'packages', 'widgets');

const bundleTarget = path.join(shipped, 'assets', 'widgets');
const sourceTarget = path.join(shipped, 'widgets-src');
const sdkTarget = path.join(shipped, 'vendor', 'kaaljyoti-sdk');

const SDK_AUTOLOADER = String.raw`<?php
/**
 * PSR-4 autoloader for the bundled Kaal Jyoti PHP SDK.
 *
 * GENERATED by plugins/wordpress/tool/build.mjs — do not edit by hand.
 *
 * The SDK is copied in rather than installed with Composer, so a site with no
 * autoloader of its own can still use it. A site that already provides
 * Kaaljyoti\Client keeps its own copy: the plugin checks before requiring
 * this file, and this file registers nothing twice.
 */

defined( 'ABSPATH' ) || exit;

if ( ! function_exists( 'kaal_jyoti_sdk_autoload' ) ) {
	/**
	 * Loads one class of the bundled SDK.
	 *
	 * @param string $class_name The fully qualified class name PHP is looking for.
	 * @return void
	 */
	function kaal_jyoti_sdk_autoload( $class_name ) {
		$prefix = 'Kaaljyoti\\';

		if ( 0 !== strpos( $class_name, $prefix ) ) {
			return;
		}

		$relative = substr( $class_name, strlen( $prefix ) );
		$path     = __DIR__ . '/src/' . str_replace( '\\', '/', $relative ) . '.php';

		if ( is_readable( $path ) ) {
			require_once $path;
		}
	}

	spl_autoload_register( 'kaal_jyoti_sdk_autoload' );
}
`;

/** @param {string} target @returns {Promise<boolean>} */
async function exists(target) {
  try {
    await stat(target);
    return true;
  } catch {
    return false;
  }
}

/** @param {string} message @returns {never} */
function fail(message) {
  console.error(`build.mjs: ${message}`);
  process.exit(1);
}

/**
 * The loader and every chunk it can load (`dist/cdn-files.json` lists them),
 * flat in `assets/widgets/`. Chunks are content-hashed, so the ones a
 * previous build left behind are removed first rather than shipped forever.
 */
async function copyWidgetBundle() {
  if (!(await exists(widgetManifest))) {
    fail(
      `the widget bundle is missing at ${path.relative(repoRoot, widgetDist)}.\n` +
        '  Build it first: pnpm --filter @kaaljyoti/widgets run build',
    );
  }
  const manifest = JSON.parse(await readFile(widgetManifest, 'utf8'));

  await mkdir(bundleTarget, { recursive: true });
  for (const name of await readdir(bundleTarget)) {
    if (name === 'v1.js' || /^kj-.*\.js$/.test(name)) await rm(path.join(bundleTarget, name));
  }
  const files = [manifest.loader, ...manifest.chunks];
  let bytes = 0;
  for (const name of files) {
    await cp(path.join(widgetDist, name), path.join(bundleTarget, name));
    bytes += (await stat(path.join(bundleTarget, name))).size;
  }

  console.log(
    `  assets/widgets/             v1.js and ${manifest.chunks.length} chunks, ${(bytes / 1024).toFixed(1)} kB from packages/widgets/dist`,
  );
}

async function copySdk() {
  if (!(await exists(sdkSource))) {
    fail(`the PHP SDK is missing at ${path.relative(repoRoot, sdkSource)}.`);
  }

  await rm(sdkTarget, { recursive: true, force: true });
  await mkdir(sdkTarget, { recursive: true });
  await cp(sdkSource, path.join(sdkTarget, 'src'), { recursive: true });
  await writeFile(path.join(sdkTarget, 'autoload.php'), SDK_AUTOLOADER, 'utf8');

  // The SDK's own composer.json, with the version bundled: what the copy is
  // and what it needs, readable without the repository (WordPress.org asks
  // for a composer.json beside bundled PHP dependencies).
  const { version } = JSON.parse(await readFile(sdkPackageJson, 'utf8'));
  const composer = JSON.parse(await readFile(sdkComposerJson, 'utf8'));
  await writeFile(
    path.join(sdkTarget, 'composer.json'),
    `${JSON.stringify({ name: composer.name, version, ...composer }, null, 2)}\n`,
    'utf8',
  );

  console.log(
    `  vendor/kaaljyoti-sdk/       sdk-php ${version}, with a PSR-4 autoloader and its composer.json`,
  );
}

const WIDGET_SOURCE_README = `Kaal Jyoti widgets: the human-readable source of assets/widgets/
=================================================================

The JavaScript in assets/widgets/ (v1.js and the kj-*.js chunks) is built,
minified, from the TypeScript and CSS in this folder. It is the
@kaaljyoti/widgets package of the Kaal Jyoti integrations, MIT licensed
(see LICENSE), by GoAppsters.

  src/                  the web components, in TypeScript, and their CSS
  scripts/build.mjs     the build (esbuild); it writes dist/
  package.json          the package and the versions of its build tools
  tsconfig*.json        the TypeScript settings the build uses

To rebuild the files in assets/widgets/:

  1. Install Node.js 20 or later.
  2. In this folder run:
       npm install esbuild@0.27 typescript@6 @types/node
       node scripts/build.mjs
  3. dist/v1.js and dist/kj-*.js are the files in assets/widgets/, with the
     same names (each chunk's name carries a hash of its contents).

Nothing in this folder is loaded by WordPress; it is here so the shipped
JavaScript can be read and rebuilt.
`;

/**
 * The readable source of the minified widget files.
 *
 * WordPress.org asks for human-readable code: a minified file has to come
 * with its source, or a link to it. The widget bundle is minified, so its
 * TypeScript and CSS, and the build that turns them into the bundle, ship in
 * `widgets-src/`. The checking tsconfig extends the workspace's base, which
 * is not in the plugin, so a copy of the base goes in beside it.
 */
async function copyWidgetSource() {
  await rm(sourceTarget, { recursive: true, force: true });
  await mkdir(path.join(sourceTarget, 'scripts'), { recursive: true });

  await cp(path.join(widgetPackage, 'src'), path.join(sourceTarget, 'src'), { recursive: true });
  await cp(
    path.join(widgetPackage, 'scripts', 'build.mjs'),
    path.join(sourceTarget, 'scripts', 'build.mjs'),
  );
  for (const name of ['package.json', 'LICENSE', 'tsconfig.build.json']) {
    await cp(path.join(widgetPackage, name), path.join(sourceTarget, name));
  }
  await cp(
    path.join(repoRoot, 'tsconfig.base.json'),
    path.join(sourceTarget, 'tsconfig.base.json'),
  );

  const tsconfig = (await readFile(path.join(widgetPackage, 'tsconfig.json'), 'utf8'))
    .replace('"../../tsconfig.base.json"', '"./tsconfig.base.json"')
    .replace(/"include": \[[^\]]*\]/, '"include": ["src/**/*.ts", "scripts/**/*.mjs"]');
  await writeFile(path.join(sourceTarget, 'tsconfig.json'), tsconfig, 'utf8');
  await writeFile(path.join(sourceTarget, 'README.txt'), WIDGET_SOURCE_README, 'utf8');

  const files = (await readdir(sourceTarget, { recursive: true, withFileTypes: true })).filter(
    (entry) => entry.isFile(),
  ).length;
  console.log(
    `  widgets-src/                ${files} files: the readable source of assets/widgets/`,
  );
}

/** Patterns `zip` leaves out of `kaaljyoti/`. */
const ZIP_EXCLUDES = [
  '*.DS_Store',
  '*/.*',
  '*/node_modules/*',
  '*/tests/*',
  '*/dist/*',
  '*.map',
  '*.log',
];

/** What must never be in the zip, checked on its listing after it is written. */
const FORBIDDEN_IN_ZIP = [
  /(^|\/)\.[^/]+/,
  /(^|\/)node_modules\//,
  /(^|\/)tests?\//,
  /(^|\/)wporg-assets\//,
  /(^|\/)(composer\.(json|lock)|phpunit\.xml|phpcs\.xml(\.dist)?)$/,
  /\.(map|log|zip)$/,
];

async function writeZip() {
  const distDir = path.join(pluginRoot, 'dist');
  const zipPath = path.join(distDir, 'kaaljyoti.zip');

  await mkdir(distDir, { recursive: true });
  await rm(zipPath, { force: true });

  // Only `kaaljyoti/` goes in, so the dev tree's `vendor/` — phpunit, phpcs
  // and the rest — the tests and the directory screenshots in `wporg-assets/`
  // are outside the zip by construction. The exclusions catch what an editor
  // or an install could leave inside it.
  execFileSync('zip', ['-r', '-q', zipPath, 'kaaljyoti', '-x', ...ZIP_EXCLUDES], {
    cwd: pluginRoot,
    stdio: 'inherit',
  });

  const listing = execFileSync('unzip', ['-Z1', zipPath], { encoding: 'utf8' }).trim().split('\n');
  const stray = listing.filter((name) => FORBIDDEN_IN_ZIP.some((pattern) => pattern.test(name)));
  if (stray.length > 0) fail(`the zip holds files that must not ship:\n  ${stray.join('\n  ')}`);
  const files = listing.filter((name) => !name.endsWith('/')).length;

  const { size } = await stat(zipPath);
  console.log(`  dist/kaaljyoti.zip         ${(size / 1024).toFixed(1)} kB, ${files} files`);
}

console.log('Kaal Jyoti for WordPress — building kaaljyoti/');
await copyWidgetBundle();
await copySdk();
await copyWidgetSource();

if (process.argv.includes('--zip')) {
  await writeZip();
}

console.log('Done.');
