#!/usr/bin/env node
/**
 * `openapi/openapi.json` → `lib/src/generated/*.dart`.
 *
 * Design decision 1: our own generator. `openapi-generator`'s Dart output
 * drags in `built_value` or `dio`; `json_serializable` would force
 * `build_runner` on every consumer of the SDK. This emits plain Dart —
 * immutable classes with `final` fields, a `fromJson` factory and a `toJson`
 * that omits nulls — and nothing a caller has to install.
 *
 * What it writes:
 *
 *   lib/src/generated/_json.dart       cast helpers (`strict-casts` is on)
 *   lib/src/generated/labelled_id.dart the one shape every document shares
 *   lib/src/generated/models.dart      every request, document and nested class
 *   lib/src/generated/operations.dart  the operation table the contract test walks
 *   lib/src/generated/version.dart     the two version constants
 *
 * The output is committed so a reader of the package can see the shapes
 * without running anything; `--check` regenerates into `.dart_tool/`, formats
 * that copy the same way, and compares byte for byte, so CI fails on a stale
 * file rather than shipping models that describe an API we no longer have.
 *
 * Usage: `node tool/gen.mjs [--check]`.
 */

import { spawn } from 'node:child_process';
import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const packageDir = dirname(dirname(fileURLToPath(import.meta.url)));
const schemaFile = join(packageDir, '../../openapi/openapi.json');
const outDir = join(packageDir, 'lib/src/generated');
const checkDir = join(packageDir, '.dart_tool/gen-check');
const dart = process.env.DART ?? 'dart';

const HEADER = (
  what,
) => `// GENERATED by \`pnpm --filter sdk-dart run gen\` from openapi/openapi.json.
// Do not edit by hand: \`pnpm --filter sdk-dart run gen:check\` fails the build
// when this file and the snapshot disagree.
//
// ${what}
`;

// ---------------------------------------------------------------------------
// The shared naming contract
// ---------------------------------------------------------------------------

/**
 * Request and document names, mirroring `packages/sdk-ts/src/types.ts`.
 *
 * The two SDKs are read side by side, so a shape must not be `DashaRequest`
 * in TypeScript and `KundliDashaRequest` in Dart. The names follow the method
 * list in the design doc rather than the operation ids — `kj.panchang.daily()`
 * answers a `DailyPanchangDocument`, so that is what the class is called even
 * though the operation is `postPanchang`.
 *
 * A missing entry is a hard error rather than a guess: a new operation in the
 * snapshot should be named deliberately in both SDKs.
 */
const REQUEST_NAMES = {
  postKundli: 'KundliRequest',
  postKundliDasha: 'DashaRequest',
  postKundliVargas: 'VargasRequest',
  postKundliChalit: 'ChalitRequest',
  postKundliYogas: 'YogasRequest',
  postKundliShadbala: 'ShadbalaRequest',
  postKundliBhavaBala: 'BhavaBalaRequest',
  postKundliAshtakavarga: 'AshtakavargaRequest',
  postKundliGrahaDrishti: 'GrahaDrishtiRequest',
  postKundliMaitri: 'MaitriRequest',
  postKundliPace: 'PaceRequest',
  postKundliSpecialLagnas: 'SpecialLagnasRequest',
  postKundliTripataki: 'TripatakiRequest',
  postKundliSarvatobhadra: 'SarvatobhadraRequest',
  postKundliNakshatra28: 'Nakshatra28Request',
  postKundliSadeSati: 'SadeSatiRequest',
  postKundliEvents: 'EventsRequest',
  postKundliKotaChakra: 'KotaChakraRequest',
  postKundliChart: 'KundliChartRequest',
  postPanchang: 'PanchangRequest',
  postPanchangMuhurta: 'MuhurtaRequest',
  postPanchangMonth: 'PanchangMonthRequest',
  postEphemerisMonth: 'EphemerisMonthRequest',
  postCalendarVikramSamvat: 'VikramSamvatRequest',
  postJaiminiKarakas: 'JaiminiKarakasRequest',
  postJaiminiArudhaPadas: 'JaiminiArudhaPadasRequest',
  postJaiminiAspects: 'JaiminiAspectsRequest',
  postJaiminiKarakamsha: 'JaiminiKarakamshaRequest',
  postKpChart: 'KpChartRequest',
  postVarshphal: 'VarshphalRequest',
  postVarshphalBala: 'VarshphalBalaRequest',
  postVarshphalSahams: 'VarshphalSahamsRequest',
  postVarshphalYogas: 'VarshphalYogasRequest',
  postVarshphalDasha: 'VarshphalDashaRequest',
  postTransitNow: 'TransitNowRequest',
  postTransitScan: 'TransitScanRequest',
  postTransitEvents: 'TransitEventsRequest',
  postMatchAshtakoot: 'MatchAshtakootRequest',
  postMatchCompare: 'MatchCompareRequest',
  postMatchBatch: 'MatchBatchRequest',
  postReportsLagna: 'ReportLagnaRequest',
  postReportsNakshatra: 'ReportNakshatraRequest',
  postHoroscope: 'HoroscopeRequest',
  postReportsHouseLords: 'ReportHouseLordsRequest',
  postReportsGrahas: 'ReportGrahasRequest',
  postReportsYogas: 'ReportYogasRequest',
  postReportsVimshottari: 'ReportVimshottariRequest',
  postReportsVarshphal: 'ReportVarshphalRequest',
  postReportsLifeAreas: 'ReportLifeAreasRequest',
  postReportsKundli: 'ReportKundliRequest',
  postPdfKundli: 'PdfKundliRequest',
  postPdfMatch: 'PdfMatchRequest',
  postPdfVarshphal: 'PdfVarshphalRequest',
  postPdfPanchangMonth: 'PdfPanchangMonthRequest',
};

/**
 * Names for the documents that are not `$ref`s to a named schema.
 *
 * Everything else takes its name from `components.schemas`, which already
 * agrees with the TypeScript aliases.
 */
const INLINE_DOCUMENT_NAMES = {
  getHealth: 'HealthDocument',
  getTimezone: 'TimezoneDocument',
  postMatchBatch: 'BatchDocument',
  getPlaces: 'PlacesDocument',
};

/**
 * Names for the `meta` members that are not a `$ref` either.
 *
 * `GET /v1/reference/{list}` and `GET /v1/timezone` report something narrower
 * than {@link Meta}: nothing was computed, so there is no ayanamsa and no
 * timezone to name.
 */
const INLINE_META_NAMES = {
  getReferenceList: 'ReferenceMeta',
  getTimezone: 'TimezoneMeta',
  getPlaces: 'PlacesMeta',
};

/**
 * Schemas whose own name cannot be used verbatim in Dart.
 *
 * `Error` is a `dart:core` class; shadowing it in the SDK's one public library
 * would break `catch (e) { if (e is Error) … }` in every file that imports us.
 */
const SCHEMA_RENAMES = { Error: 'ErrorBody' };

/** Nested shapes worth a hand-picked name instead of a path-derived one. */
const NESTED_RENAMES = {
  ErrorBodyError: 'ErrorDetail',
  // `MaitriDocument` is a map of maps, so the path-derived name for the leaf
  // is `MaitriDocumentValueValue`, which says nothing.
  MaitriDocumentValueValue: 'MaitriRelation',
  // `{start, end}` — the muhurta windows of both panchang documents.
  DailyPanchangDocumentAbhijitMuhurta: 'TimeWindow',
  // One house system's cusps in `ChalitDocument`, which publishes four.
  ChalitDocumentEqual: 'ChalitHouses',
  // Pratyantardasha, sookshma and pran dasha (levels 3–5) nest one `children[]` deeper each; the path-derived
  // names grow a `ChildrenItem` per level and outrun the line length.
  DashaDocumentSystemsVimshottariPeriodsItemChildrenItemChildrenItem:
    'DashaVimshottariPratyantardasha',
  DashaVimshottariPratyantardashaChildrenItem: 'DashaVimshottariSookshma',
  DashaVimshottariSookshmaChildrenItem: 'DashaVimshottariPran',
  DashaDocumentSystemsCharaPeriodsItemChildrenItemChildrenItem: 'DashaCharaPratyantardasha',
  DashaCharaPratyantardashaChildrenItem: 'DashaCharaSookshma',
  DashaCharaSookshmaChildrenItem: 'DashaCharaPran',
  ReadingLagnaDocumentLagna: 'ReadingLagna',
  ReadingNakshatraDocumentNakshatra: 'ReadingNakshatra',
  // One house of the house-lords reading: its sign, the lord, where the lord sits.
  ReadingHouseLordsDocumentHouseLordsItem: 'HouseLord',
  // `{text}`, the same in both readings.
  ReadingLagnaEntry: 'ReadingEntry',
  // `{en?, hi?}` — every text of the report routes, and their disclaimer.
  ReadingEntryText: 'LocalizedText',
  // The summaries (API 0.9.1): `{level, text}` overall, and `{area, level,
  // text}` per life area — the same two shapes in the horoscope and the
  // varshphal reading, whichever of the two the generator meets first.
  HoroscopeDocumentSummary: 'ReadingSummary',
  VarshphalReadingDocumentSummary: 'ReadingSummary',
  HoroscopeDocumentAreasItem: 'AreaSummary',
  VarshphalReadingDocumentAreasItem: 'AreaSummary',
  // One transit behind a horoscope: for the site, not the reader.
  HoroscopeDocumentBasisItem: 'HoroscopeTransit',
  // One graha of the grahas reading; one yoga of the yogas reading.
  ReadingGrahasDocumentGrahasItem: 'GrahaReading',
  ReadingYogasDocumentYogasItem: 'YogaReading',
  // One mahadasha of the Vimshottari reading, its antardashas, and the
  // houses it acts on.
  VimshottariReadingDocumentPeriodsItem: 'MahadashaReading',
  MahadashaReadingAntardashasItem: 'AntardashaReading',
  MahadashaReadingAreasItem: 'MahadashaArea',
  // One period (mudda dasha) of the varshphal year.
  VarshphalReadingDocumentMonthsItem: 'VarshphalPeriod',
  // One ingress or station of the year's transit calendar.
  TransitEventsDocumentEventsItem: 'TransitEvent',
  // The life-areas reading: its summary, one area, and a dasha period that
  // brings the area forward.
  LifeAreasDocumentSummary: 'LifeAreasSummary',
  LifeAreasDocumentAreasItem: 'LifeArea',
  LifeAreaPeriodsItem: 'LifeAreaPeriod',
  // The kundli report's parts. The gateway infers their schemas apart from
  // the parts' own routes, so they are not always the same shapes; they get
  // names of their own rather than the generated `KundliReportDocument…`.
  KundliReportDocumentGrahasItem: 'KundliReportGraha',
  KundliReportDocumentHouseLordsItem: 'KundliReportHouseLord',
  KundliReportDocumentLifeAreas: 'KundliReportLifeAreas',
  KundliReportDocumentVarshphal: 'KundliReportVarshphal',
  KundliReportDocumentVimshottari: 'KundliReportVimshottari',
  KundliReportVimshottariPeriodsItem: 'KundliReportMahadasha',
  PlacesDocumentPlacesItem: 'Place',
  // The letterhead of a PDF (Enterprise): the same shape on all four PDF
  // routes, named after whichever the generator meets first.
  PdfKundliRequestBranding: 'PdfBranding',
  PdfMatchRequestBranding: 'PdfBranding',
  PdfVarshphalRequestBranding: 'PdfBranding',
  PdfPanchangMonthRequestBranding: 'PdfBranding',
};

/**
 * `anyOf` fields of a string or an object, each with a hand-written class.
 *
 * `options.disclaimer` is `"default"`, `"off"` or `{name, url?}`. A generated
 * class cannot be two shapes at once, and `Object?` would leave the caller to
 * guess the wire; {@link disclaimerDart} is the one class that is both.
 */
const UNION_NAMES = {
  'CalculationOptions.disclaimer': 'Disclaimer',
  'PdfKundliOptions.disclaimer': 'Disclaimer',
};

/**
 * Prose for the shapes the snapshot writes inline and therefore never
 * describes. Everything else takes its doc comment from the schema.
 */
const DESCRIPTIONS = {
  Birth: [
    'A wall clock, a place, and at most one of `timezone` / `utcOffset`.',
    '',
    'Every birth-based operation takes the same object, so it is worth',
    'building once and passing everywhere. The "at most one zone" rule is the',
    "API's: sending both is a `400`.",
  ].join('\n'),
  'CalculationOptions.disclaimer': [
    'The closing line of a report: [Disclaimer.standard] (the default),',
    '[Disclaimer.off], or [Disclaimer.consult] with your own name.',
    '',
    'Accepted on every route; only the report routes answer with one.',
  ].join('\n'),
  CalculationOptions: [
    'Ayanamsa, label languages, engine pin and disclaimer.',
    '',
    'Every field is optional; the gateway applies its own defaults',
    '(`lahiri`, `en`) for the ones left out. The house system is not here:',
    'only the kundli PDF takes one, on [PdfKundliOptions].',
  ].join('\n'),
  PdfKundliOptions: [
    "The kundli PDF's options: [CalculationOptions] plus `houseSystem`.",
    '',
    '`houseSystem` picks the bhava chalit the PDF prints (default',
    '`placidus`); every other route refuses it with a `400`.',
  ].join('\n'),
  'CalculationOptions.language': [
    'The languages labels should come back in.',
    '',
    "Always a list here — `language: ['en', 'hi']` — and a single",
    'language is written to the wire as the bare string the API documents.',
  ].join('\n'),
};
DESCRIPTIONS['PdfKundliOptions.language'] = DESCRIPTIONS['CalculationOptions.language'];
DESCRIPTIONS['PdfKundliOptions.disclaimer'] = DESCRIPTIONS['CalculationOptions.disclaimer'];

/** `GET /v1/reference/{list}` rows are open by design — no class for them. */
const OPERATIONS_WITHOUT_DOCUMENT = new Set(['getReferenceList']);

// ---------------------------------------------------------------------------
// Names
// ---------------------------------------------------------------------------

const RESERVED = new Set([
  'abstract',
  'as',
  'assert',
  'async',
  'await',
  'base',
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'covariant',
  'default',
  'deferred',
  'do',
  'dynamic',
  'else',
  'enum',
  'export',
  'extends',
  'extension',
  'external',
  'factory',
  'false',
  'final',
  'finally',
  'for',
  'function',
  'get',
  'hide',
  'if',
  'implements',
  'import',
  'in',
  'interface',
  'is',
  'late',
  'library',
  'mixin',
  'new',
  'null',
  'of',
  'on',
  'operator',
  'part',
  'required',
  'rethrow',
  'return',
  'sealed',
  'set',
  'show',
  'static',
  'super',
  'switch',
  'sync',
  'this',
  'throw',
  'true',
  'try',
  'typedef',
  'var',
  'void',
  'when',
  'while',
  'with',
  'yield',
  // Members every Dart object already has.
  'hashCode',
  'runtimeType',
  'toString',
  'noSuchMethod',
  'toJson',
  'fromJson',
]);

/** `utc_offset` / `UtcOffset` / `utcOffset` → `['utc', 'offset']`. */
function words(name) {
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean);
}

function pascal(name) {
  return words(name)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join('');
}

function camel(name) {
  const p = pascal(name);
  const lower = p[0].toLowerCase() + p.slice(1);
  return RESERVED.has(lower) ? `${lower}Value` : lower;
}

// ---------------------------------------------------------------------------
// Dart source helpers
// ---------------------------------------------------------------------------

function quote(text) {
  return `'${text.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\$/g, '\\$')}'`;
}

/** A description, as `///` lines, with the blank lines OpenAPI allows kept. */
function docComment(text, indent = '') {
  if (!text) return [];
  return String(text)
    .trim()
    .split('\n')
    .map((line) => line.replace(/\s+$/, ''))
    .map((line) => (line ? `${indent}/// ${line}` : `${indent}///`));
}

// ---------------------------------------------------------------------------
// Structural identity
// ---------------------------------------------------------------------------

/**
 * A schema reduced to the part of it Dart can see.
 *
 * `birth` and `options` are written out inline in 35-odd request bodies, and
 * two of those copies differ only in a `default` (`KP` defaults the ayanamsa
 * to `krishnamurti`). Validation keywords, defaults and prose change nothing
 * about the generated class, so they are dropped before comparing: what is
 * left is the shape, and equal shapes share one class.
 */
function shapeKey(schema) {
  // At the root, `{"type": ["null", "object"]}` and `{"type": "object"}` are
  // the same class: whether the *field* may be null is the field's business.
  // Inside, nullability is kept — `{a: string}` and `{a: string | null}` are
  // different classes.
  return JSON.stringify(shapeOf(schema, true));
}

function shapeOf(schema, root = false) {
  if (!schema || typeof schema !== 'object') return schema ?? null;
  if (schema.$ref) return { $ref: schema.$ref };
  const out = {};
  if (schema.type !== undefined) {
    let declared = Array.isArray(schema.type) ? [...schema.type].sort() : schema.type;
    if (root && Array.isArray(declared)) {
      const real = declared.filter((t) => t !== 'null');
      declared = real.length === 1 ? real[0] : real.length === 0 ? 'null' : real;
    }
    out.type = declared;
  }
  if (schema.anyOf) out.anyOf = schema.anyOf.map(shapeOf);
  if (schema.properties) {
    out.properties = {};
    for (const key of Object.keys(schema.properties).sort()) {
      out.properties[key] = shapeOf(schema.properties[key]);
    }
  }
  if (schema.required) out.required = [...schema.required].sort();
  if (schema.items) out.items = shapeOf(schema.items);
  if (schema.additionalProperties === true) out.additionalProperties = true;
  else if (schema.additionalProperties && typeof schema.additionalProperties === 'object') {
    out.additionalProperties = shapeOf(schema.additionalProperties);
  }
  return out;
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * A resolved Dart type.
 *
 * `kind` drives the `fromJson` / `toJson` expressions; `dart` is what the
 * field is declared as. `nullable` is tracked separately from `dart` so a
 * `List<T>?` knows its element type is not itself nullable.
 */
function type(kind, extra = {}) {
  return { kind, nullable: false, ...extra };
}

function render(t) {
  const q = t.nullable ? '?' : '';
  switch (t.kind) {
    case 'string':
      return `String${q}`;
    case 'int':
      return `int${q}`;
    case 'double':
      return `double${q}`;
    case 'bool':
      return `bool${q}`;
    case 'stringList':
      return `List<String>${q}`;
    case 'class':
    case 'union':
      return `${t.name}${q}`;
    case 'list':
      return `List<${render(t.of)}>${q}`;
    case 'map':
      return `Map<String, ${render(t.of)}>${q}`;
    case 'json':
      return `Map<String, dynamic>${q}`;
    case 'any':
      return 'Object?';
    default:
      throw new Error(`unknown kind ${t.kind}`);
  }
}

/** The expression that reads `expr` (an `Object?`) as a non-null `t`. */
function readNonNull(t, expr) {
  switch (t.kind) {
    case 'string':
      return `asString(${expr})`;
    case 'int':
      return `asInt(${expr})`;
    case 'double':
      return `asDouble(${expr})`;
    case 'bool':
      return `asBool(${expr})`;
    case 'stringList':
      return `asStringList(${expr})`;
    case 'class':
      return `${t.name}.fromJson(asMap(${expr}))`;
    case 'union':
      return `${t.name}.fromJson(${expr})`;
    case 'json':
      return `asMap(${expr})`;
    case 'any':
      return expr;
    case 'list': {
      const inner = read(t.of, 'e');
      return inner === 'e' ? `asList(${expr})` : `asList(${expr}).map((e) => ${inner}).toList()`;
    }
    case 'map': {
      const inner = read(t.of, 'v');
      return inner === 'v'
        ? `asMap(${expr})`
        : `asMap(${expr}).map((k, v) => MapEntry(k, ${inner}))`;
    }
    default:
      throw new Error(`unknown kind ${t.kind}`);
  }
}

/** The expression that reads `expr` as `t`, nullability included. */
function read(t, expr) {
  if (!t.nullable) return readNonNull(t, expr);
  if (t.kind === 'any') return expr;
  const simple = {
    string: 'asStringOrNull',
    int: 'asIntOrNull',
    double: 'asDoubleOrNull',
    bool: 'asBoolOrNull',
  };
  if (simple[t.kind]) return `${simple[t.kind]}(${expr})`;
  return `${expr} == null ? null : ${readNonNull(t, expr)}`;
}

/** The expression that turns the field `name` of type `t` back into JSON. */
function write(t, name) {
  const q = t.nullable ? '?' : '';
  switch (t.kind) {
    case 'class':
    case 'union':
      return `${name}${q}.toJson()`;
    case 'list':
      return writesPlainly(t.of) ? name : `${name}${q}.map((e) => ${write(t.of, 'e')}).toList()`;
    case 'map':
      return writesPlainly(t.of)
        ? name
        : `${name}${q}.map((k, v) => MapEntry(k, ${write(t.of, 'v')}))`;
    default:
      return name;
  }
}

/** True when a value of `t` is already JSON and needs no mapping. */
function writesPlainly(t) {
  return ['string', 'int', 'double', 'bool', 'json', 'any', 'stringList'].includes(t.kind);
}

// ---------------------------------------------------------------------------
// The model graph
// ---------------------------------------------------------------------------

const doc = JSON.parse(await readFile(schemaFile, 'utf8'));
const pubspec = await readFile(join(packageDir, 'pubspec.yaml'), 'utf8');
const sdkVersion = /^version:\s*(\S+)\s*$/m.exec(pubspec)?.[1];
if (!sdkVersion) throw new Error('pubspec.yaml has no version:');

/** name → { name, description, origin, fields } for every class but `LabelledId`. */
const classes = new Map();
/** shapeKey → class name, so one shape is one class. */
const shapes = new Map();
/** Constructs the generator could not represent exactly, reported at the end. */
const fallbacks = [];

function refName(ref) {
  const raw = ref.replace('#/components/schemas/', '');
  return SCHEMA_RENAMES[raw] ?? raw;
}

/**
 * Resolve one schema to a Dart type, defining classes as it goes.
 *
 * `hint` is the name a class would get if this schema turns out to need one:
 * the owning class plus the property, so `KundliDocument.birth` is
 * `KundliDocumentBirth` and the value type of its `positions` map is
 * `KundliDocumentPositionsValue`.
 */
function resolve(schema, hint, origin) {
  if (!schema || typeof schema !== 'object') return type('any');
  if (schema.$ref) return type('class', { name: refName(schema.$ref) });

  if (schema.anyOf) return resolveAnyOf(schema, hint, origin);

  const declared = Array.isArray(schema.type) ? schema.type : schema.type ? [schema.type] : [];
  const nullable = declared.includes('null');
  const rest = declared.filter((t) => t !== 'null');

  if (rest.length === 0 && nullable) {
    // `{"type": "null"}`: the engine always answers null here (choghadiya's
    // `planet`). There is no Dart type for "always null" worth having, so the
    // field is an `Object?` the caller can ignore.
    fallbacks.push(`${origin}: \`type: "null"\` → Object?`);
    return type('any', { nullable: true });
  }
  if (rest.length > 1) {
    fallbacks.push(`${origin}: \`type: ${JSON.stringify(declared)}\` → Object?`);
    return type('any', { nullable: true });
  }

  const base = rest[0] ?? (schema.properties ? 'object' : schema.items ? 'array' : undefined);
  let resolved;
  switch (base) {
    case 'string':
      resolved = type('string');
      break;
    case 'integer':
      resolved = type('int');
      break;
    case 'number':
      // `number` is `double`, except where the schema enumerates whole
      // numbers (`levels: 1 | 2 | 3 | 4 | 5`) and an int reads better on the wire.
      resolved = type(allIntegerEnum(schema) ? 'int' : 'double');
      break;
    case 'boolean':
      resolved = type('bool');
      break;
    case 'array':
      resolved = type('list', { of: resolve(schema.items, `${hint}Item`, `${origin}[]`) });
      break;
    case 'object':
      resolved = resolveObject(schema, hint, origin);
      break;
    default:
      fallbacks.push(`${origin}: no \`type\` → Object?`);
      resolved = type('any', { nullable: true });
  }
  return nullable ? { ...resolved, nullable: true } : resolved;
}

function allIntegerEnum(schema) {
  return Array.isArray(schema.enum) && schema.enum.every((v) => Number.isInteger(v));
}

function resolveObject(schema, hint, origin) {
  if (schema.properties) return type('class', { name: defineClass(schema, hint, origin) });
  const extra = schema.additionalProperties;
  if (extra && typeof extra === 'object') {
    return type('map', { of: resolve(extra, `${hint}Value`, `${origin}{}`) });
  }
  // `additionalProperties: true`, or no properties at all: an open row.
  return type('json');
}

function resolveAnyOf(schema, hint, origin) {
  const branches = schema.anyOf;
  const isNull = (b) =>
    b.type === 'null' ||
    (Array.isArray(b.type) && !b.type.includes('object') && b.type.every((t) => t === 'null'));
  const nullable =
    branches.some(isNull) || branches.some((b) => Array.isArray(b.type) && b.type.includes('null'));
  const real = branches.filter((b) => !isNull(b));

  // `options.language`: `'en'` or `['en', 'hi']` on the wire. Callers get one
  // type — a list — and a single-element list goes out as the bare string.
  const stringOrList =
    real.length === 2 &&
    real.some((b) => b.type === 'string') &&
    real.some((b) => b.type === 'array' && b.items?.type === 'string');
  if (stringOrList) return type('stringList', { nullable });

  if (UNION_NAMES[origin]) return type('union', { name: UNION_NAMES[origin], nullable: true });

  if (real.length === 1) return { ...resolve(real[0], hint, origin), nullable: true };

  // `levels: 1 | 2 | 3 | 4 | 5` arrives as five single-value `number` branches.
  if (real.length > 1 && real.every((b) => b.type === 'number' && allIntegerEnum(b))) {
    return type('int', { nullable });
  }
  if (real.length > 1 && real.every((b) => b.type === real[0].type && !b.properties)) {
    return { ...resolve(real[0], hint, origin), nullable };
  }

  fallbacks.push(`${origin}: \`anyOf\` of ${real.length} unrelated shapes → Object?`);
  return type('any', { nullable: true });
}

/**
 * Define (or reuse) the class for an object schema and answer its name.
 *
 * Equal shapes share a class, which is what keeps `Birth` and
 * `CalculationOptions` single classes instead of 35 copies apiece.
 */
function defineClass(schema, preferred, origin) {
  const key = shapeKey(schema);
  const existing = shapes.get(key);
  if (existing) return existing;

  let name = NESTED_RENAMES[preferred] ?? preferred;
  if (classes.has(name)) {
    let n = 2;
    while (classes.has(`${name}${n}`)) n += 1;
    fallbacks.push(`${origin}: name ${name} was taken → ${name}${n}`);
    name = `${name}${n}`;
  }

  const entry = {
    name,
    description: DESCRIPTIONS[name] ?? schema.description,
    origin,
    fields: [],
  };
  classes.set(name, entry);
  shapes.set(key, name);

  if (!schema.properties) {
    // A document that is a bare map (`MaitriDocument` is planet → planet →
    // relation). Dart has no place to hang `fromJson` on a `Map`, so the class
    // wraps the map and subscripts through to it; `toJson` still answers the
    // map itself, so the wire shape is unchanged.
    entry.valueType = resolve(
      schema.additionalProperties && typeof schema.additionalProperties === 'object'
        ? schema.additionalProperties
        : {},
      `${name}Value`,
      `${origin}{}`,
    );
    return name;
  }

  const required = new Set(schema.required ?? []);
  const used = new Map();
  for (const [wire, propSchema] of Object.entries(schema.properties)) {
    let dartName = camel(wire);
    if (used.has(dartName)) {
      fallbacks.push(
        `${name}: \`${wire}\` and \`${used.get(dartName)}\` both camelCase to ${dartName}`,
      );
      dartName = `${dartName}${pascal(wire)}`;
    }
    used.set(dartName, wire);
    const fieldType = resolve(propSchema, name + pascal(wire), `${name}.${wire}`);
    entry.fields.push({
      wire,
      name: dartName,
      description: DESCRIPTIONS[`${name}.${wire}`] ?? propSchema.description,
      // Anything the schema does not require, and anything it requires but
      // allows to be null, is a `T?` in Dart: the gateway omits keys it has
      // nothing to say about.
      type: { ...fieldType, nullable: fieldType.nullable || !required.has(wire) },
    });
  }
  return name;
}

// ---------------------------------------------------------------------------
// Walk the document
// ---------------------------------------------------------------------------

const schemas = doc.components.schemas;
const bodyOf = (op) => op.requestBody?.content?.['application/json']?.schema;
const okOf = (op) => op.responses?.['200']?.content?.['application/json']?.schema;

// `birth` and `options` first, so the 35 inline copies find them already
// defined and every request refers to the same two classes.
const kundliBody = bodyOf(doc.paths['/v1/kundli'].post);
defineClass(kundliBody.properties.birth, 'Birth', 'POST /v1/kundli birth');
defineClass(kundliBody.properties.options, 'CalculationOptions', 'POST /v1/kundli options');
// The kundli PDF's options add `house_system` (the chalit it prints), which no
// other route takes.
const pdfKundliBody = bodyOf(doc.paths['/v1/pdf/kundli'].post);
defineClass(pdfKundliBody.properties.options, 'PdfKundliOptions', 'POST /v1/pdf/kundli options');

// A `/v1/panchang/month` day carries the same `{amanta, purnimanta}` pair as
// `masa` that `/v1/calendar/vikram-samvat` answers, and `PanchangMonthDocument`
// comes first; name the pair after the document so the day reuses it.
defineClass(
  schemas.VikramSamvatDocument,
  'VikramSamvatDocument',
  '#/components/schemas/VikramSamvatDocument',
);

for (const [rawName, schema] of Object.entries(schemas)) {
  if (rawName === 'LabelledId') continue; // its own file
  defineClass(schema, SCHEMA_RENAMES[rawName] ?? rawName, `#/components/schemas/${rawName}`);
}

const operations = [];
for (const [path, item] of Object.entries(doc.paths)) {
  for (const [method, op] of Object.entries(item)) {
    if (!op.operationId) continue;
    const id = op.operationId;
    const body = bodyOf(op);
    let requestType = null;
    if (body) {
      const name = REQUEST_NAMES[id];
      if (!name) throw new Error(`${id} has a request body but no name in REQUEST_NAMES`);
      requestType = defineClass(body, name, `${method.toUpperCase()} ${path} body`);
    }

    let documentType = null;
    const ok = okOf(op);
    if (ok && !OPERATIONS_WITHOUT_DOCUMENT.has(id)) {
      const data = ok.properties?.data ?? ok;
      const name = INLINE_DOCUMENT_NAMES[id];
      documentType = data.$ref
        ? refName(data.$ref)
        : defineClass(
            data,
            name ?? `${pascal(id)}Document`,
            `${method.toUpperCase()} ${path} data`,
          );
    }
    const metaName = INLINE_META_NAMES[id];
    if (metaName && ok?.properties?.meta && !ok.properties.meta.$ref) {
      defineClass(ok.properties.meta, metaName, `${method.toUpperCase()} ${path} meta`);
    }

    operations.push({
      id,
      method: method.toUpperCase(),
      path,
      tag: op.tags?.[0] ?? '',
      requestType,
      documentType,
    });
  }
}

// ---------------------------------------------------------------------------
// Emit
// ---------------------------------------------------------------------------

function emitClass(entry) {
  const out = [];
  out.push(...docComment(entry.description));
  if (entry.description) out.push('///');
  out.push(`/// Wire shape: \`${entry.origin}\`.`);
  out.push(`class ${entry.name} {`);

  if (entry.valueType) return emitMapClass(entry, out);

  out.push(`  const ${entry.name}({`);
  for (const f of entry.fields) {
    out.push(`    ${f.type.nullable ? '' : 'required '}this.${f.name},`);
  }
  out.push('  });');
  out.push('');

  out.push(`  factory ${entry.name}.fromJson(Map<String, dynamic> json) {`);
  out.push(`    return ${entry.name}(`);
  for (const f of entry.fields) {
    out.push(`      ${f.name}: ${read(f.type, `json[${quote(f.wire)}]`)},`);
  }
  out.push('    );');
  out.push('  }');
  out.push('');

  for (const f of entry.fields) {
    out.push(...docComment(f.description, '  '));
    if (f.wire !== f.name) {
      if (f.description) out.push('  ///');
      out.push(`  /// Wire key: \`${f.wire}\`.`);
    }
    out.push(`  final ${render(f.type)} ${f.name};`);
    out.push('');
  }

  out.push('  /// This value as JSON, with every null key left out.');
  out.push('  Map<String, dynamic> toJson() {');
  out.push('    final json = <String, dynamic>{};');
  for (const f of entry.fields) {
    const value = write(f.type, f.name);
    if (!f.type.nullable) {
      out.push(`    json[${quote(f.wire)}] = ${value};`);
    } else if (f.type.kind === 'stringList') {
      // A single language goes out as the string the gateway documents.
      out.push(`    final ${f.name} = this.${f.name};`);
      out.push(`    if (${f.name} != null) {`);
      out.push(
        `      json[${quote(f.wire)}] = ${f.name}.length == 1 ? ${f.name}.first : ${f.name};`,
      );
      out.push('    }');
    } else if (writesPlainly(f.type)) {
      out.push(`    if (${f.name} != null) {`);
      out.push(`      json[${quote(f.wire)}] = ${f.name};`);
      out.push('    }');
    } else {
      // A local, so the `.toJson()` mapping needs no `?.` inside a null check.
      out.push(`    final ${f.name} = this.${f.name};`);
      out.push(`    if (${f.name} != null) {`);
      out.push(`      json[${quote(f.wire)}] = ${write({ ...f.type, nullable: false }, f.name)};`);
      out.push('    }');
    }
  }
  out.push('    return json;');
  out.push('  }');
  out.push('}');
  return out.join('\n');
}

/**
 * A holder of the string constants an enum property accepts.
 *
 * Enums stay `String` on the fields themselves — the gateway adds values
 * between SDK releases and a Dart enum would turn that into a crash — but the
 * values it lists today are worth spelling once so callers can autocomplete
 * them instead of quoting a slug from the docs.
 */
function emitConstants(name, description, values) {
  const out = [];
  out.push(...docComment(description));
  out.push(`abstract final class ${name} {`);
  for (const value of values) {
    out.push(`  /// \`${value}\``);
    out.push(`  static const String ${camel(value)} = ${quote(value)};`);
    out.push('');
  }
  out.push('  /// Every value the snapshot lists, in its order.');
  out.push(`  static const List<String> values = <String>[`);
  for (const value of values) out.push(`    ${quote(value)},`);
  out.push('  ];');
  out.push('}');
  return out.join('\n');
}

/** A document that is a bare map: the class wraps it and subscripts through. */
function emitMapClass(entry, out) {
  const value = render(entry.valueType);
  const mapType = `Map<String, ${value}>`;
  out.push(`  /// Wraps the [values] this document is.`);
  out.push(`  const ${entry.name}(this.values);`);
  out.push('');
  out.push(`  /// Reads the map, keyed as the API keys it.`);
  out.push(`  factory ${entry.name}.fromJson(Map<String, dynamic> json) {`);
  out.push(`    return ${entry.name}(`);
  out.push(`      json.map((k, v) => MapEntry(k, ${read(entry.valueType, 'v')})),`);
  out.push('    );');
  out.push('  }');
  out.push('');
  out.push('  /// The document itself, which has no fields of its own.');
  out.push(`  final ${mapType} values;`);
  out.push('');
  out.push('  /// The entry under [key], or null when the API left it out.');
  out.push(`  ${value}${entry.valueType.nullable ? '' : '?'} operator [](String key) =>`);
  out.push('      values[key];');
  out.push('');
  out.push('  /// This value as JSON.');
  out.push('  Map<String, dynamic> toJson() =>');
  const inner = write(entry.valueType, 'v');
  out.push(
    inner === 'v'
      ? '      Map<String, dynamic>.from(values);'
      : `      values.map((k, v) => MapEntry(k, ${inner}));`,
  );
  out.push('}');
  return out.join('\n');
}

const jsonDart = `${HEADER('Cast helpers. `strict-casts` is on, so a `Map<String, dynamic>` value\n// cannot be assigned to a `String` without one; doing it here keeps the\n// generated `fromJson` bodies one expression each and puts a readable\n// message on a malformed payload instead of a bare `TypeCastException`.')}
/// Thrown when a payload does not have the shape the schema promised.
class KaaljyotiFormatException implements FormatException {
  /// Wraps [value], which was supposed to be a [wanted].
  KaaljyotiFormatException(this.wanted, this.value);

  /// The Dart type the schema calls for.
  final String wanted;

  /// The value that arrived instead.
  final Object? value;

  @override
  String get message =>
      'expected $wanted, got \${value == null ? 'null' : '\${value.runtimeType} ($value)'}';

  @override
  Object? get source => value;

  @override
  int? get offset => null;

  @override
  String toString() => 'KaaljyotiFormatException: $message';
}

Never _bad(String wanted, Object? value) =>
    throw KaaljyotiFormatException(wanted, value);

/// [value] as a JSON object.
Map<String, dynamic> asMap(Object? value) =>
    value is Map<String, dynamic> ? value : _bad('an object', value);

/// [value] as a JSON array.
List<Object?> asList(Object? value) =>
    value is List<Object?> ? value : _bad('an array', value);

/// [value] as a string.
String asString(Object? value) =>
    value is String ? value : _bad('a string', value);

/// [value] as an integer.
int asInt(Object? value) => value is int
    ? value
    : value is double && value == value.roundToDouble()
        ? value.toInt()
        : _bad('an integer', value);

/// [value] as a double, accepting the integers JSON writes for whole numbers.
double asDouble(Object? value) =>
    value is num ? value.toDouble() : _bad('a number', value);

/// [value] as a boolean.
bool asBool(Object? value) => value is bool ? value : _bad('a boolean', value);

/// [value] as the SDK's list-of-languages shape: the API writes a lone
/// language as a bare string and several as an array.
List<String> asStringList(Object? value) => value is String
    ? <String>[value]
    : asList(value).map(asString).toList();

/// [value] as a JSON object, or null.
Map<String, dynamic>? asMapOrNull(Object? value) =>
    value == null ? null : asMap(value);

/// [value] as a JSON array, or null.
List<Object?>? asListOrNull(Object? value) =>
    value == null ? null : asList(value);

/// [value] as a string, or null.
String? asStringOrNull(Object? value) => value == null ? null : asString(value);

/// [value] as an integer, or null.
int? asIntOrNull(Object? value) => value == null ? null : asInt(value);

/// [value] as a double, or null.
double? asDoubleOrNull(Object? value) => value == null ? null : asDouble(value);

/// [value] as a boolean, or null.
bool? asBoolOrNull(Object? value) => value == null ? null : asBool(value);
`;

const labelled = schemas.LabelledId;
const labelledDart = `${HEADER('`LabelledId`, the shape every named id in every document shares.')}
import '_json.dart';

${docComment(labelled.description).join('\n')}
///
/// Wire shape: \`#/components/schemas/LabelledId\`.
class LabelledId {
  /// An id with the name the gateway attached to it.
  const LabelledId({required this.id, required this.name, this.names});

  /// Reads a \`{id, name, names?}\` object.
  factory LabelledId.fromJson(Map<String, dynamic> json) {
    return LabelledId(
      id: asString(json['id']),
      name: asString(json['name']),
      names: json['names'] == null
          ? null
          : asMap(json['names']).map((k, v) => MapEntry(k, asString(v))),
    );
  }

${docComment(labelled.properties.id.description, '  ').join('\n')}
  final String id;

${docComment(labelled.properties.name.description, '  ').join('\n')}
  final String name;

${docComment(labelled.properties.names.description, '  ').join('\n')}
  final Map<String, String>? names;

  /// This value as JSON, with every null key left out.
  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{'id': id, 'name': name};
    final names = this.names;
    if (names != null) json['names'] = names;
    return json;
  }

  @override
  String toString() => 'LabelledId($id, $name)';

  @override
  bool operator ==(Object other) =>
      other is LabelledId &&
      other.id == id &&
      other.name == name &&
      _sameNames(other.names, names);

  @override
  int get hashCode => Object.hash(
        id,
        name,
        names == null
            ? null
            : Object.hashAllUnordered(
                names!.entries.map((e) => Object.hash(e.key, e.value)),
              ),
      );
}

bool _sameNames(Map<String, String>? a, Map<String, String>? b) {
  if (a == null || b == null) return a == b;
  if (a.length != b.length) return false;
  for (final entry in a.entries) {
    if (b[entry.key] != entry.value) return false;
  }
  return true;
}
`;

/**
 * `Disclaimer`, written by hand because it is a string or an object.
 *
 * The snapshot is checked rather than trusted: a third preset or a new key in
 * the object would otherwise be silently missing from the class, so either
 * one stops the generator until this template learns it.
 */
const disclaimerSchema = kundliBody.properties.options.properties.disclaimer;
{
  const presets = disclaimerSchema?.anyOf?.find((b) => b.type === 'string')?.enum ?? [];
  const object = disclaimerSchema?.anyOf?.find((b) => b.type === 'object');
  const keys = Object.keys(object?.properties ?? {}).sort();
  if (presets.join() !== 'default,off' || keys.join() !== 'name,url') {
    throw new Error(
      `options.disclaimer is now ${JSON.stringify(disclaimerSchema)}; update disclaimerDart`,
    );
  }
}
const disclaimerDart = `/// How a report closes: \`options.disclaimer\`.
///
/// The report routes (every \`reports\` method, and \`horoscope\`) end with
/// a \`disclaimer\` line in each requested language. [standard] is the
/// API's own line, [off] leaves it out, and [Disclaimer.consult] names the
/// astrologer a reader should consult instead of "an astrologer".
///
/// Wire shape: \`"default"\`, \`"off"\` or \`{name, url?}\`.
class Disclaimer {
  const Disclaimer._(this.preset)
      : name = null,
        url = null;

  /// Names [name] (1–80 characters) and, when given, [url] in the line:
  /// "…consult [name] ([url])."
  const Disclaimer.consult(String this.name, {this.url}) : preset = null;

  /// Reads either wire shape.
  factory Disclaimer.fromJson(Object? json) {
    if (json is String) return Disclaimer._(json);
    final map = asMap(json);
    return Disclaimer.consult(
      asString(map['name']),
      url: asStringOrNull(map['url']),
    );
  }

  /// \`"default"\`: "These predictions are indicative. For a reading of your
  /// own chart, consult an astrologer." What the API sends when asked nothing.
  static const Disclaimer standard = Disclaimer._('default');

  /// \`"off"\`: the answer has no \`disclaimer\` at all.
  static const Disclaimer off = Disclaimer._('off');

  /// \`default\` or \`off\`, or null for a [Disclaimer.consult].
  final String? preset;

  /// The astrologer to consult, or null for a preset.
  final String? name;

  /// Where to find them (a URI, at most 200 characters), or null.
  final String? url;

  /// The preset as its string, or \`{name, url?}\`.
  Object toJson() {
    final preset = this.preset;
    if (preset != null) return preset;
    final json = <String, dynamic>{'name': name};
    final url = this.url;
    if (url != null) json['url'] = url;
    return json;
  }

  @override
  bool operator ==(Object other) =>
      other is Disclaimer &&
      other.preset == preset &&
      other.name == name &&
      other.url == url;

  @override
  int get hashCode => Object.hash(preset, name, url);

  @override
  String toString() => 'Disclaimer(\${preset ?? name})';
}`;

const modelsDart = `${HEADER('Every request body, every answer document, and the anonymous objects\n// nested inside them. Classes are alphabetical; `LabelledId` has its own file.')}
import '_json.dart';
import 'labelled_id.dart';

${[
  emitConstants(
    'Ayanamsa',
    'The ayanamsas `CalculationOptions.ayanamsa` accepts.',
    kundliBody.properties.options.properties.ayanamsa.enum,
  ),
  emitConstants(
    'HouseSystem',
    'The house systems `PdfKundliOptions.houseSystem` accepts.',
    pdfKundliBody.properties.options.properties.house_system.enum,
  ),
  emitConstants(
    'Varga',
    'The divisional charts `KundliChartRequest.varga` and `VargasRequest.vargas` accept.',
    bodyOf(doc.paths['/v1/kundli/chart'].post).properties.varga.enum,
  ),
  emitConstants(
    'ChartStyle',
    'The styles `KundliChartRequest.style` accepts.',
    bodyOf(doc.paths['/v1/kundli/chart'].post).properties.style.enum,
  ),
  disclaimerDart,
  ...[...classes.values()]
    .sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0))
    .map(emitClass),
].join('\n\n')}
`;

const operationsDart = `${HEADER('The operation table: what the client calls and what the contract test walks.')}
/// One operation of the Kaal Jyoti API, as \`openapi/openapi.json\` describes it.
class Operation {
  /// Describes one operation.
  const Operation({
    required this.id,
    required this.method,
    required this.path,
    required this.tag,
    this.requestType,
    this.documentType,
  });

  /// The \`operationId\` from the snapshot, e.g. \`postKundliDasha\`.
  final String id;

  /// The HTTP verb, upper case.
  final String method;

  /// The path, with its \`{list}\` placeholders intact.
  final String path;

  /// The tag the operation is grouped under, which is the client namespace.
  final String tag;

  /// The request class, or null when the operation takes no JSON body.
  final String? requestType;

  /// The \`data\` class, or null when the answer has no named shape.
  final String? documentType;

  @override
  String toString() => '$method $path ($id)';
}

/// Every operation in the snapshot, in the order the document lists them.
const List<Operation> operations = <Operation>[
${operations
  .map((op) => {
    const lines = [
      '  Operation(',
      `    id: ${quote(op.id)},`,
      `    method: ${quote(op.method)},`,
      `    path: ${quote(op.path)},`,
      `    tag: ${quote(op.tag)},`,
    ];
    if (op.requestType) lines.push(`    requestType: ${quote(op.requestType)},`);
    if (op.documentType) lines.push(`    documentType: ${quote(op.documentType)},`);
    lines.push('  ),');
    return lines.join('\n');
  })
  .join('\n')}
];
`;

const versionDart = `${HEADER('The two versions the client reports and the contract test pins.')}
/// The version of this package, from \`pubspec.yaml\`.
///
/// Sent as \`X-KJ-Client: sdk-dart/$sdkVersion\`.
const String sdkVersion = ${quote(sdkVersion)};

/// The \`info.version\` of the OpenAPI snapshot these models were built from.
const String openApiVersion = ${quote(doc.info.version)};
`;

const files = {
  '_json.dart': jsonDart,
  'labelled_id.dart': labelledDart,
  'models.dart': modelsDart,
  'operations.dart': operationsDart,
  'version.dart': versionDart,
};

// ---------------------------------------------------------------------------
// Write, format, compare
// ---------------------------------------------------------------------------

function run(command, args, cwd, quiet = false) {
  return new Promise((resolve_, reject) => {
    const child = spawn(command, args, {
      cwd,
      stdio: quiet ? ['inherit', 'ignore', 'inherit'] : 'inherit',
    });
    child.on('error', reject);
    child.on('close', (code) =>
      code === 0 ? resolve_() : reject(new Error(`${command} ${args.join(' ')} exited ${code}`)),
    );
  });
}

async function writeAll(dir) {
  await mkdir(dir, { recursive: true });
  for (const [name, source] of Object.entries(files)) {
    await writeFile(join(dir, name), source);
  }
}

const check = process.argv.includes('--check');

if (check) {
  // Formatting is part of the committed bytes, so the candidate is formatted
  // the same way before it is compared — and inside the package, so `dart
  // format` reads the same language version from the same pubspec.
  await rm(checkDir, { recursive: true, force: true });
  await writeAll(checkDir);
  await run(dart, ['format', '--suppress-analytics', checkDir], packageDir, true);

  const differ = [];
  for (const name of Object.keys(files)) {
    const wanted = await readFile(join(checkDir, name));
    const current = await readFile(join(outDir, name)).catch(() => null);
    if (current === null) differ.push(`${name} (missing)`);
    else if (!current.equals(wanted)) differ.push(name);
  }
  const extra = (await readdir(outDir).catch(() => [])).filter((n) => !(n in files));
  for (const name of extra) differ.push(`${name} (not generated any more)`);
  await rm(checkDir, { recursive: true, force: true });

  if (differ.length > 0) {
    console.error(
      `lib/src/generated is out of date with openapi/openapi.json:\n` +
        differ.map((name) => `  - ${name}`).join('\n') +
        `\nRun: pnpm --filter sdk-dart run gen`,
    );
    process.exit(1);
  }
  console.log(`lib/src/generated is current (${Object.keys(files).length} files).`);
} else {
  await writeAll(outDir);
  await run(dart, ['format', '--suppress-analytics', 'lib/src/generated'], packageDir);
  console.log(
    `Wrote ${Object.keys(files).length} files, ${classes.size + 1} classes, ` +
      `${operations.length} operations from openapi ${doc.info.version}.`,
  );
  if (fallbacks.length > 0) {
    console.log('Constructs with no exact Dart shape:');
    for (const line of [...new Set(fallbacks)]) console.log(`  - ${line}`);
  }
}
