/**
 * `openapi/openapi.json` → `src/generated/openapi.d.ts`.
 *
 * The output is committed rather than built on install for two reasons: a
 * reader of the published package can see the shapes without running
 * anything, and `npm install` of an SDK must not need a generator. The price
 * is that the file can fall behind the snapshot, which is what `--check`
 * exists to catch — CI runs it and fails the build rather than shipping types
 * that describe an API we no longer have.
 *
 * `alphabetize` is on so that a reordered `paths` object in the snapshot does
 * not show up as a diff here; only a real change to a shape does.
 */

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

const packageDir = dirname(dirname(fileURLToPath(import.meta.url)));
const schemaFile = join(packageDir, '../../openapi/openapi.json');
const outFile = join(packageDir, 'src/generated/openapi.d.ts');

const HEADER = `/**
 * Generated by \`pnpm --filter @kaaljyoti/sdk run gen\` from \`openapi/openapi.json\`.
 * Generated, do not edit. Hand-named aliases over these live in \`src/types.ts\`.
 */

`;

/** The file as it should be, from the snapshot on disk. */
async function generate() {
  const ast = await openapiTS(new URL(`file://${schemaFile}`), {
    alphabetize: true,
    exportType: false,
  });
  return HEADER + astToString(ast);
}

const wanted = await generate();

if (process.argv.includes('--check')) {
  const current = await readFile(outFile, 'utf8').catch(() => null);
  if (current !== wanted) {
    const where = relative(process.cwd(), outFile);
    console.error(
      current === null
        ? `${where} is missing. Run: pnpm --filter @kaaljyoti/sdk run gen`
        : `${where} is out of date with openapi/openapi.json. Run: pnpm --filter @kaaljyoti/sdk run gen`,
    );
    process.exit(1);
  }
  console.log('src/generated/openapi.d.ts is current.');
} else {
  await mkdir(dirname(outFile), { recursive: true });
  await writeFile(outFile, wanted);
  console.log(`Wrote src/generated/openapi.d.ts (${(wanted.length / 1024).toFixed(1)} KB).`);
}
